apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-fast-240-worker06
spec:
  capacity:
    storage: 220Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-fast
  local:
    path: /var/mnt/fast-240
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - worker06