apiVersion: v1
stringData:
    .dockerconfigjson: ENC[AES256_GCM,data:zqfxL4U3WskTK5FOKrvsWWPAs/mybE5c4J4UYXgksm3Zcpae9PxUhL4UYchNQ4tAIFLFNlIxKUItyPQ/v3Tvjqyz9p0U4GCxHzkN/h6U8on8QW60YXn1qgt0zEhTtBgCEBuC0hD6++BZufxYWCOp7D4OOTdYDNeuwZGknAGZwyg9W4RvNmB/k/x85aeDZLj1qqo=,iv:HmH/3hT7UFxBUdplnYBMXSvj2yPa3Ef6wDb+Jc2a40A=,tag:GNfrpPKSSkfXdTwpmZk1NQ==,type:str]
kind: Secret
type: kubernetes.io/dockerconfigjson
metadata:
    creationTimestamp: null
    name: ghcr-image-pull-secret
    namespace: flux-system
    labels:
        reconcile.fluxcd.io/watch: Enabled
sops:
    lastmodified: "2026-01-04T01:35:40Z"
    mac: ENC[AES256_GCM,data:4WkdDLtqG1IUXTZlC3oDLBrxpuFlYdOYsgu6qKFpoq7kP55Qqd9AwDhup7aqbouMAnE0bpDnv1+fcjF0yL+cxAqePd8B4QZ+sn0TypPKqRxJx1Xsgst3+A37qtXL62XcQTB+44DYxVIj6nZevmF41qcJw8/rFPReupkNZk2/t5g=,iv:dXNBZ7U5EZxyoRabryaBQrPKlniNR3o7mMNmiRWSDAE=,tag:nMoeJJ2TdDTwrQsMdOfLgQ==,type:str]
    pgp:
        - created_at: "2025-12-19T04:32:28Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4D3ufNC3rOtvoSAQdAeIn2wnFe2gKhZrIZzr3YdFQbcs7aVDRzUEifzCqQ+k8w
            BKa5h91ElcVbbJ8uYlj0CP+vq3iVgfXmJL1dQA/NgLusHzVPAPHpmoFaJQbUXqbw
            0l4BEFn/ZcxKIV605tuu07/sGVnOxUyV8jVWpmLNR93spUQwoA3WqFM7JIiRTbim
            zP+RMxZGsjTprVzjIf7mcW+s2VIh9eTi56T4zo23RMsrqeg1J4u2TGo2T9L+tiNu
            =+iqw
            -----END PGP MESSAGE-----
          fp: 910E6AB3B6B93104BC0D0F5AD48349BEF211483F
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
---
apiVersion: homerow.ca/v1
kind: SyncSecret
metadata:
    name: ghcr-image-pull-secret
spec:
    secret:
        name: ghcr-image-pull-secret
        namespace: flux-system
    destinationNamespaces:
        - small-indie-bot
        - crypto
sops:
    lastmodified: "2026-01-04T01:35:40Z"
    mac: ENC[AES256_GCM,data:4WkdDLtqG1IUXTZlC3oDLBrxpuFlYdOYsgu6qKFpoq7kP55Qqd9AwDhup7aqbouMAnE0bpDnv1+fcjF0yL+cxAqePd8B4QZ+sn0TypPKqRxJx1Xsgst3+A37qtXL62XcQTB+44DYxVIj6nZevmF41qcJw8/rFPReupkNZk2/t5g=,iv:dXNBZ7U5EZxyoRabryaBQrPKlniNR3o7mMNmiRWSDAE=,tag:nMoeJJ2TdDTwrQsMdOfLgQ==,type:str]
    pgp:
        - created_at: "2025-12-19T04:32:28Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4D3ufNC3rOtvoSAQdAeIn2wnFe2gKhZrIZzr3YdFQbcs7aVDRzUEifzCqQ+k8w
            BKa5h91ElcVbbJ8uYlj0CP+vq3iVgfXmJL1dQA/NgLusHzVPAPHpmoFaJQbUXqbw
            0l4BEFn/ZcxKIV605tuu07/sGVnOxUyV8jVWpmLNR93spUQwoA3WqFM7JIiRTbim
            zP+RMxZGsjTprVzjIf7mcW+s2VIh9eTi56T4zo23RMsrqeg1J4u2TGo2T9L+tiNu
            =+iqw
            -----END PGP MESSAGE-----
          fp: 910E6AB3B6B93104BC0D0F5AD48349BEF211483F
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
