apiVersion: v1
stringData:
    .dockerconfigjson: ENC[AES256_GCM,data:zqfxL4U3WskTK5FOKrvsWWPAs/mybE5c4J4UYXgksm3Zcpae9PxUhL4UYchNQ4tAIFLFNlIxKUItyPQ/v3Tvjqyz9p0U4GCxHzkN/h6U8on8QW60YXn1qgt0zEhTtBgCEBuC0hD6++BZufxYWCOp7D4OOTdYDNeuwZGknAGZwyg9W4RvNmB/k/x85aeDZLj1qqo=,iv:HmH/3hT7UFxBUdplnYBMXSvj2yPa3Ef6wDb+Jc2a40A=,tag:GNfrpPKSSkfXdTwpmZk1NQ==,type:str]
kind: Secret
type: kubernetes.io/dockerconfigjson
metadata:
    creationTimestamp: null
    name: ghcr-image-pull-secret
    namespace: flux-system
    labels:
        reconcile.fluxcd.io/watch: Enabled
sops:
    lastmodified: "2026-01-04T01:47:17Z"
    mac: ENC[AES256_GCM,data:XxqY6I4Mgd2LrNVGmMhg/eYbV75nfqcogp9tAIGFt5uZ6Cp1/Bj1fJj3rFPz9Po8nihzmzLFKKViAjSCRxHUW65nPLP8oa8H9v8eH5TOwforXpI2UtTJQA8T2OkXK9W+5mLJu+NZsuLdV18gidCGizHJegzutqRTPApJ341hSTA=,iv:5Z7QWXSJztFAH8j7OeHL911rg0abLjtQRjfCwWSVHXg=,tag:/O7KWwLVhj+Fww5yZCMjZQ==,type:str]
    pgp:
        - created_at: "2025-12-19T04:32:28Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4D3ufNC3rOtvoSAQdAeIn2wnFe2gKhZrIZzr3YdFQbcs7aVDRzUEifzCqQ+k8w
            BKa5h91ElcVbbJ8uYlj0CP+vq3iVgfXmJL1dQA/NgLusHzVPAPHpmoFaJQbUXqbw
            0l4BEFn/ZcxKIV605tuu07/sGVnOxUyV8jVWpmLNR93spUQwoA3WqFM7JIiRTbim
            zP+RMxZGsjTprVzjIf7mcW+s2VIh9eTi56T4zo23RMsrqeg1J4u2TGo2T9L+tiNu
            =+iqw
            -----END PGP MESSAGE-----
          fp: 910E6AB3B6B93104BC0D0F5AD48349BEF211483F
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
---
apiVersion: homerow.ca/v1
kind: SyncSecret
metadata:
    name: ghcr-image-pull-secret
spec:
    secret:
        name: ghcr-image-pull-secret
        namespace: flux-system
    destinationNamespaces:
        - small-indie-bot
        - bitcoin
sops:
    lastmodified: "2026-01-04T01:47:17Z"
    mac: ENC[AES256_GCM,data:XxqY6I4Mgd2LrNVGmMhg/eYbV75nfqcogp9tAIGFt5uZ6Cp1/Bj1fJj3rFPz9Po8nihzmzLFKKViAjSCRxHUW65nPLP8oa8H9v8eH5TOwforXpI2UtTJQA8T2OkXK9W+5mLJu+NZsuLdV18gidCGizHJegzutqRTPApJ341hSTA=,iv:5Z7QWXSJztFAH8j7OeHL911rg0abLjtQRjfCwWSVHXg=,tag:/O7KWwLVhj+Fww5yZCMjZQ==,type:str]
    pgp:
        - created_at: "2025-12-19T04:32:28Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4D3ufNC3rOtvoSAQdAeIn2wnFe2gKhZrIZzr3YdFQbcs7aVDRzUEifzCqQ+k8w
            BKa5h91ElcVbbJ8uYlj0CP+vq3iVgfXmJL1dQA/NgLusHzVPAPHpmoFaJQbUXqbw
            0l4BEFn/ZcxKIV605tuu07/sGVnOxUyV8jVWpmLNR93spUQwoA3WqFM7JIiRTbim
            zP+RMxZGsjTprVzjIf7mcW+s2VIh9eTi56T4zo23RMsrqeg1J4u2TGo2T9L+tiNu
            =+iqw
            -----END PGP MESSAGE-----
          fp: 910E6AB3B6B93104BC0D0F5AD48349BEF211483F
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
