apiVersion: v1
stringData:
    VPN_SERVICE_PROVIDER: ENC[AES256_GCM,data:waActR67,iv:NSokKZA/XHaIC/JvS+YeGfEtH/qpNFPAMBvM06BAmCA=,tag:pvxr6lyf2YgIUpDZMo+bpQ==,type:str]
    VPN_TYPE: ENC[AES256_GCM,data:9YfVqhRccs64,iv:+HQV3b2eufJD5fgufgE4SeQuRZM4ux59oyMXT8L0hvg=,tag:G1fVgJ/WqIdOKNo5YvgcXw==,type:str]
    WIREGUARD_ENDPOINT_IP: ENC[AES256_GCM,data:DSZEWElk7swPIRo=,iv:p7SdPnLWJboQketqI0rOZnXXhYzVZTRTRpWHOtcQvXE=,tag:E+hp2HaO5toixKqDx4RfXw==,type:str]
    WIREGUARD_ENDPOINT_PORT: ENC[AES256_GCM,data:hHd9ubM=,iv:U7zpLZeo77BlyNjgdvNUx0FV0t2bM+UDaF6Guc29geA=,tag:TarjU96ZWqYHLeOmwdqYJQ==,type:str]
    WIREGUARD_MTU: ENC[AES256_GCM,data:KWs7pA==,iv:Izs6oHr8Q5iU5tVBIME+tYg0W+90Pd7dfNeT+HwetOI=,tag:3bD9Zli2vU7t45wBWDWe/w==,type:str]
    DOT: ENC[AES256_GCM,data:tEPJ,iv:Y/u3EVdNxLQyf/5vjtV3qgYrGwRt3w1vbKZjqoNrDoY=,tag:axyCIneEy666o2DdSqRmqg==,type:str]
    FIREWALL_OUTBOUND_SUBNETS: ENC[AES256_GCM,data:FonQBQag+nCFOz7P5J/uEdtTpZO2maY85w461ODCZoUYZ7vQS0d3IjQ=,iv:IdqqTN/oRUBv34Yl/8fvtK7Ux8vSbDM0mE2mHVgWogc=,tag:ubxdIngAyslDp2J5ZzlIpQ==,type:str]
    HEALTH_HTTP_ADDRESS: ENC[AES256_GCM,data:0M92FT7ANguqiPCMYws=,iv:Q78IGTsalX3nmyGA1EjfYu81vc76xBK0kisLGqEb9l4=,tag:6qK50IyWnM3vWTDkh6ADDQ==,type:str]
    TZ: ENC[AES256_GCM,data:CYUr59nj2ikXpEVM0Put,iv:Yi/LxKWS8MERHqkKTFWjChhV29LcOMgbn7NXCgs5fAk=,tag:Mx7smZDMN3IUksjMDOi81Q==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: gluetun-wg
    namespace: flux-system
    labels:
        reconcile.fluxcd.io/watch: Enabled
sops:
    lastmodified: "2026-01-11T20:26:27Z"
    mac: ENC[AES256_GCM,data:6AnhsSC6Dc70WymjwmtaLsrHMDktIgT15TJt5wWum4IqylABAabLSiHpIMhenLm6fpjxYbmknQDLkyYwejUmB5ZP9DJACOFyb+OvGEloTmIDwQa/L+CEVNtVoCcaljyc3Hi+LcUkmlFmaexE2G3LnV5fcfp6s/9nFsC6EtMMKoI=,iv:8S2ZNk7mNV1xzb2Zw3gNP7HJlNVQNveL9hU8cAqSeHg=,tag:G42M1DqnIg3YjO76HMLznQ==,type:str]
    pgp:
        - created_at: "2025-12-19T04:32:28Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4D3ufNC3rOtvoSAQdAeIn2wnFe2gKhZrIZzr3YdFQbcs7aVDRzUEifzCqQ+k8w
            BKa5h91ElcVbbJ8uYlj0CP+vq3iVgfXmJL1dQA/NgLusHzVPAPHpmoFaJQbUXqbw
            0l4BEFn/ZcxKIV605tuu07/sGVnOxUyV8jVWpmLNR93spUQwoA3WqFM7JIiRTbim
            zP+RMxZGsjTprVzjIf7mcW+s2VIh9eTi56T4zo23RMsrqeg1J4u2TGo2T9L+tiNu
            =+iqw
            -----END PGP MESSAGE-----
          fp: 910E6AB3B6B93104BC0D0F5AD48349BEF211483F
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
---
apiVersion: homerow.ca/v1
kind: SyncSecret
metadata:
    name: gluetun-wg
spec:
    secret:
        name: gluetun-wg
        namespace: flux-system
    destinationNamespaces:
        - media
sops:
    lastmodified: "2026-01-11T20:26:27Z"
    mac: ENC[AES256_GCM,data:6AnhsSC6Dc70WymjwmtaLsrHMDktIgT15TJt5wWum4IqylABAabLSiHpIMhenLm6fpjxYbmknQDLkyYwejUmB5ZP9DJACOFyb+OvGEloTmIDwQa/L+CEVNtVoCcaljyc3Hi+LcUkmlFmaexE2G3LnV5fcfp6s/9nFsC6EtMMKoI=,iv:8S2ZNk7mNV1xzb2Zw3gNP7HJlNVQNveL9hU8cAqSeHg=,tag:G42M1DqnIg3YjO76HMLznQ==,type:str]
    pgp:
        - created_at: "2025-12-19T04:32:28Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4D3ufNC3rOtvoSAQdAeIn2wnFe2gKhZrIZzr3YdFQbcs7aVDRzUEifzCqQ+k8w
            BKa5h91ElcVbbJ8uYlj0CP+vq3iVgfXmJL1dQA/NgLusHzVPAPHpmoFaJQbUXqbw
            0l4BEFn/ZcxKIV605tuu07/sGVnOxUyV8jVWpmLNR93spUQwoA3WqFM7JIiRTbim
            zP+RMxZGsjTprVzjIf7mcW+s2VIh9eTi56T4zo23RMsrqeg1J4u2TGo2T9L+tiNu
            =+iqw
            -----END PGP MESSAGE-----
          fp: 910E6AB3B6B93104BC0D0F5AD48349BEF211483F
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
