apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - external-secrets
  - secret-sync
  - ghcr-image-pull-secret.sops.yaml
  - gluetun-wg.sops.yaml
  - namespace.yaml
  - vault