apiVersion: v1
stringData:
    NEWT_ID: ENC[AES256_GCM,data:rn+3FQ6M5WJvwitY5eg2,iv:w24dhu5GUR+Ys1mFvCcrdkWLbmtzf9wU0B51HXTbcck=,tag:oCi03gJyo5hWUEY1Q3UP7g==,type:str]
    NEWT_SECRET: ENC[AES256_GCM,data:tDtkPt/zjN0+6BPGUf6uzxoHSpRO8cHVf11jMefJCeSIxG9qUbjoftw3BE1fmpwd,iv:erny7kc01k3mY2FkrQZQmL73C08UB9kjHn0K6c8X8xA=,tag:FFFcvcMVBDjEaQ3BvyZOfQ==,type:str]
    PANGOLIN_ENDPOINT: ENC[AES256_GCM,data:j9FXCEv1EltVLvxRFB+bu+9UEHrBsgezqw==,iv:oDn9Yor5ypQ93uzxFuFF0zwgTyr3hpXoU7HM7N1f9K4=,tag:JP+oBKYtHfVBEObAg1mGfA==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: newt-configuration
    namespace: admin
    labels:
        reconcile.fluxcd.io/watch: Enabled
sops:
    lastmodified: "2026-01-03T22:33:32Z"
    mac: ENC[AES256_GCM,data:MlgwB+SRzwyW7jo++gTvSiKzMU59ohnwniraN98iZY67K7Tn4qiNFk9jqKEViZd2LahTMeoxmuhJSm/k5tKCPEKrePggfCrcEcGAGGTqbNZTWQGPDaY63xe9NGVIynrmr1t+MbcWy8nLQW8aeQ9YP259l8+WViOZJRsF4VD0NB4=,iv:Snm0EngoqVFIzduoGfgNgRKmRvwt//90bLf+Axqj7E4=,tag:RkkqHHCt4bbK9OCFvMCgpA==,type:str]
    pgp:
        - created_at: "2025-12-19T04:32:28Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4D3ufNC3rOtvoSAQdAeIn2wnFe2gKhZrIZzr3YdFQbcs7aVDRzUEifzCqQ+k8w
            BKa5h91ElcVbbJ8uYlj0CP+vq3iVgfXmJL1dQA/NgLusHzVPAPHpmoFaJQbUXqbw
            0l4BEFn/ZcxKIV605tuu07/sGVnOxUyV8jVWpmLNR93spUQwoA3WqFM7JIiRTbim
            zP+RMxZGsjTprVzjIf7mcW+s2VIh9eTi56T4zo23RMsrqeg1J4u2TGo2T9L+tiNu
            =+iqw
            -----END PGP MESSAGE-----
          fp: 910E6AB3B6B93104BC0D0F5AD48349BEF211483F
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
