apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: proxmox-csi-plugin
  namespace: flux-system
spec:
  interval: 15m
  url: oci://ghcr.io/sergelogvinov/charts/proxmox-csi-plugin
  timeout: 3m
  ref:
    tag: 0.5.5
  layerSelector:
    mediaType: "application/vnd.cncf.helm.chart.content.v1.tar+gzip"
    operation: copy
