---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - cert-manager
  - external-secrets
  - garage
  - mailrise
  - newt
  - registry
  - secret-sync
  - traefik
  - unifi
  - vault