apiVersion: v1
stringData:
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:OW6izgHTykcvESADTFA7BAZjsbP1is/nR9KbmaFZDwg=,iv:kmWn1w91y5ow4lYxBUPWpzxen1wwrbpwYoiWPOZmytc=,tag:SMt9xDvMETusYxyZxWwCgQ==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: immich-postgres-configuration
    namespace: other-webapps
    labels:
        reconcile.fluxcd.io/watch: Enabled
sops:
    lastmodified: "2026-01-04T03:26:42Z"
    mac: ENC[AES256_GCM,data:iV4QrPwzlILdwiDoqvyoTyUE/oP9V3VurpZhPKo7LJsq3lx+fAVj914xPWcfKTD/HgJt4qH6BnslFvX7ifDH2btZJsSHFVZQBvuArGEjBCdfxi1aL6JxWOK+/LyA3Y+dNnygkyOCzk0uHTQ/W2cc9iiwQUiGZRoUV7bAHQDux6w=,iv:7cSYP6zegLXHx6C9/+Yp8cEn0nMzDnlGzNAk24lYNho=,tag:TwBWsjhLl8nbFxYLlAGoGg==,type:str]
    pgp:
        - created_at: "2025-12-19T04:32:28Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4D3ufNC3rOtvoSAQdAeIn2wnFe2gKhZrIZzr3YdFQbcs7aVDRzUEifzCqQ+k8w
            BKa5h91ElcVbbJ8uYlj0CP+vq3iVgfXmJL1dQA/NgLusHzVPAPHpmoFaJQbUXqbw
            0l4BEFn/ZcxKIV605tuu07/sGVnOxUyV8jVWpmLNR93spUQwoA3WqFM7JIiRTbim
            zP+RMxZGsjTprVzjIf7mcW+s2VIh9eTi56T4zo23RMsrqeg1J4u2TGo2T9L+tiNu
            =+iqw
            -----END PGP MESSAGE-----
          fp: 910E6AB3B6B93104BC0D0F5AD48349BEF211483F
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
