apiVersion: v1
stringData:
    DB_DATABASE_NAME: ENC[AES256_GCM,data:/56LZrxV,iv:ErleLbPZFkNMdJs5aopzwMvBoXlebwb2/BRQ+agmlGY=,tag:ZVd7er3qhJc2ADD9gC16aw==,type:str]
    DB_HOSTNAME: ENC[AES256_GCM,data:RFKKShzBaaXxB+kQjm7LVjkBpDhcx/rM3w5hLHFrpq7eTxnKQBxZPktc7YPeCjY=,iv:AqxRSlHWNfEe6KJ/+egefVpk5A11ppKX1WqcM5ZXv4o=,tag:ff3m1RrzUIQV+j4qljIJFQ==,type:str]
    DB_PASSWORD: ENC[AES256_GCM,data:UrO3Vhk27jMO+GjCFyqNEL3ysWyWqZ/MpIzAza81hNI=,iv:iajZbCR4mqJN9oh5Zi/AZ6KAxrNqDwdF6ZeX7F/G1pE=,tag:rrSW3eL0t59n/ZFcLpYJOg==,type:str]
    DB_USERNAME: ENC[AES256_GCM,data:8srGzHLM,iv:kI9h/vzdbpzXFHH5G60xdzeCRO1mBFjwCZOLi4oVhcw=,tag:DBj3RXyZSz8mLIVWv6DJaw==,type:str]
    IMMICH_VERSION: ENC[AES256_GCM,data:rpBExYinIw==,iv:pyuQfuxVYtg16N+XQdO72jN59tZrmcLO1pPG3kpL0yc=,tag:XtcY2GjfuN4gYeq4aeSN5A==,type:str]
    REDIS_HOSTNAME: ENC[AES256_GCM,data:FNnWQExLFP62Rheh56zoo+XZikuFEm3nWPgXXztnv1kzfX2mNkSKXdeFG4k=,iv:acNx9Jl08ZelBQLiNuFRreDMBwYssElt49Zf/lDVO3U=,tag:7lZwdTHscOwTAYSkRNJ52g==,type:str]
    UPLOAD_LOCATION: ENC[AES256_GCM,data:dbDVVmh5BSMS,iv:ZD4l5m/19+7je19KL0bISWQ65WAfOAPKlNPOu4PR2DY=,tag:H9Yym5Jxsw0d3JOl05DWng==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: immich-configuration
    namespace: other-webapps
    labels:
        reconcile.fluxcd.io/watch: Enabled
sops:
    lastmodified: "2026-01-04T03:25:30Z"
    mac: ENC[AES256_GCM,data:+szHdslOhMV2jPZMizvgiEtYT27PLOrEZjyRPoofQnr6ztqAoTVF7u+syYJOo1D4jL9TjqkOtd7Aq+90/b4/867ueJicPJr0VJEVNEQNdwcbHSLkDe3k5Jpk6cTL3fFtrasni1AcKFr4P+b1HVi3Vl5o6k/QvazC24ZqFTvYoRw=,iv:d2W/EFWZqnh4XqjZhF5EANMYPrIDoj34XucV/K1jJHc=,tag:S3svksj+ST3tmiUVnuKJcg==,type:str]
    pgp:
        - created_at: "2025-12-19T04:32:28Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4D3ufNC3rOtvoSAQdAeIn2wnFe2gKhZrIZzr3YdFQbcs7aVDRzUEifzCqQ+k8w
            BKa5h91ElcVbbJ8uYlj0CP+vq3iVgfXmJL1dQA/NgLusHzVPAPHpmoFaJQbUXqbw
            0l4BEFn/ZcxKIV605tuu07/sGVnOxUyV8jVWpmLNR93spUQwoA3WqFM7JIiRTbim
            zP+RMxZGsjTprVzjIf7mcW+s2VIh9eTi56T4zo23RMsrqeg1J4u2TGo2T9L+tiNu
            =+iqw
            -----END PGP MESSAGE-----
          fp: 910E6AB3B6B93104BC0D0F5AD48349BEF211483F
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
