apiVersion: v1
stringData:
    proxmox_tamland_url: ENC[AES256_GCM,data:N0pzj6K+0TbrDbUereZa5DwxvOBA,iv:Bv6FBxAp9KHZsfwWKaHvWn4GfYSOoGZusw8+VZvzFhI=,tag:UFA7YiQGJZ1y6t495+Z54A==,type:str]
    proxmox_tamland_token_id: ENC[AES256_GCM,data:2dj81sxo6nX/LN/AsrzV,iv:xv0Dln25SA+vIALIsWqTP4d762Jeecc2jBC1mJqUn4g=,tag:Wn+x7RxOglYNlGZYGNi3mg==,type:str]
    proxmox_tamland_token_secret: ENC[AES256_GCM,data:bYSaTSVfNWj+MT5JNUhkYBy4phh4M9vM+OkJiLf9OF3VXE3n,iv:bxeMJqesgyt5CPZHJW7zKCctbhomaiUH6UoQEdB5Lc0=,tag:MEXhm1/t5KPsEBHGd3ui0w==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: infra-sops-secrets
    namespace: flux-system
sops:
    lastmodified: "2025-12-19T04:57:53Z"
    mac: ENC[AES256_GCM,data:bbB7Q56/TlbqSv4DwgsmMjv/GhPHLobBWrgp8DhH04bWdGBRPo6bmDTSoVy1LHUu1UJWG1S6shXVqA2KkB/iIbiQ9UjDywKXhgR7Y7Csk97hZYtQ/LggIZWNzTbSipV2/Zt9J23CB7l546tK1Y6f3GjypAjWgM1tXa5tupr69as=,iv:zW7NODXD5VhSG0xT4vuojGhhPk+/YFHYYoJZeCdek9o=,tag:+M39/81g4vXWvtT/1C4oKQ==,type:str]
    pgp:
        - created_at: "2025-12-19T04:32:28Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4D3ufNC3rOtvoSAQdAeIn2wnFe2gKhZrIZzr3YdFQbcs7aVDRzUEifzCqQ+k8w
            BKa5h91ElcVbbJ8uYlj0CP+vq3iVgfXmJL1dQA/NgLusHzVPAPHpmoFaJQbUXqbw
            0l4BEFn/ZcxKIV605tuu07/sGVnOxUyV8jVWpmLNR93spUQwoA3WqFM7JIiRTbim
            zP+RMxZGsjTprVzjIf7mcW+s2VIh9eTi56T4zo23RMsrqeg1J4u2TGo2T9L+tiNu
            =+iqw
            -----END PGP MESSAGE-----
          fp: 910E6AB3B6B93104BC0D0F5AD48349BEF211483F
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
