apiVersion: v1
stringData:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:rj+Esfv5934w0Wp4h5kb0meAYXE=,iv:b0VZhOsuKOpgWe9Z84KOFnRxi1UnGyJuKFzCEkNfN2g=,tag:TzzhhGc9NUbL+CPm61A9UQ==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:DjDtVc/olnuKtKjIl2kjZpTRc30P542mpFp8wM2TBxs0fCsZbW2Kcw==,iv:lOOLZu7s1MKOZpqnXR4lXxL5t36oseQ3ZtfCIKWuJqY=,tag:ymskL9lTCQvRQY9B0h3R0w==,type:str]
kind: Secret
type: Opaque
metadata:
    creationTimestamp: null
    name: vault-access-key-secret
    namespace: secrets
    labels:
        reconcile.fluxcd.io/watch: Enabled
sops:
    lastmodified: "2026-01-03T06:22:26Z"
    mac: ENC[AES256_GCM,data:BWuxS8HOGPNYuiJ6J3+KgviwWs1cIs+2BSPedrhPux9gVx9Q61Yr68vSO7kELkcmircVSA3Dww92SS7X3tP6MQiYENENxvDdFS/8s8A13F47WMYZxL6UddT0w3yYTtDYu8GEPFGHF2DJcoBsqWprSTHPh8a3Cvn3eSlM6iAKWW4=,iv:UUg9OiyHPOzkJuMxUuKAutoFg1K4xwXfNwI9Qtm0hms=,tag:drD5AA5qOR4OhzviKAKqBQ==,type:str]
    pgp:
        - created_at: "2025-12-19T04:32:28Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4D3ufNC3rOtvoSAQdAeIn2wnFe2gKhZrIZzr3YdFQbcs7aVDRzUEifzCqQ+k8w
            BKa5h91ElcVbbJ8uYlj0CP+vq3iVgfXmJL1dQA/NgLusHzVPAPHpmoFaJQbUXqbw
            0l4BEFn/ZcxKIV605tuu07/sGVnOxUyV8jVWpmLNR93spUQwoA3WqFM7JIiRTbim
            zP+RMxZGsjTprVzjIf7mcW+s2VIh9eTi56T4zo23RMsrqeg1J4u2TGo2T9L+tiNu
            =+iqw
            -----END PGP MESSAGE-----
          fp: 910E6AB3B6B93104BC0D0F5AD48349BEF211483F
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
