apiVersion: v1
stringData:
    AFFINE_REVISION: ENC[AES256_GCM,data:f8apx8II,iv:9tIzB+DS6t2C09AEF8O+ClzgCIrHcmn9F13kzhWCDJg=,tag:61gLg2z3EhpQPG86PaUxEg==,type:str]
    PORT: ENC[AES256_GCM,data:Vqpyhw==,iv:z+GCuzkZcl/RG7+CZhdyF02BGJ65SOlTrtsbYSgO5+s=,tag:JkueH534wNyGG/4S9/3nDg==,type:str]
    AFFINE_SERVER_HTTPS: ENC[AES256_GCM,data:fmGbyA==,iv:AC7gK2BvCMMMriHlNLvWUoQL1oJNn4BugCCnjGop9Yk=,tag:6Hi4546gZ4deY6SgA7OI7A==,type:str]
    AFFINE_SERVER_HOST: ENC[AES256_GCM,data:4GlG1qsTIi6ybUl0OEk=,iv:aJG6aCCLlxdZQ3NFfmfSlKpmvODcLw9JviACf9tHs4k=,tag:ETzV49p2xbBb2NwNtkohmw==,type:str]
    DB_USERNAME: ENC[AES256_GCM,data:zxAi1QW3,iv:ppdiFgxoXZN4Y09EgKpwBbWyWZDH7h7cQREYSjeVAC0=,tag:rEFmazPTsT59PCfF/OvSFg==,type:str]
    DB_PASSWORD: ENC[AES256_GCM,data:G+y9rhhH2cJQ1J50v6+q8e49QiZxLgBDD+/E9WfA5Po=,iv:mzCASucotUW6T7uIZ9myYivs3dmMuNxAHPIJOp97Rbw=,tag:kp6TDW90i2F2tui9uOfOVA==,type:str]
    DB_DATABASE: ENC[AES256_GCM,data:or185sjc,iv:Pb8YXFxw6a4MZLa26TlVmp00gB995EbjXvfDs4JaG/k=,tag:NGXL8xnV2HmwOblLeL02iQ==,type:str]
    REDIS_SERVER_HOST: ENC[AES256_GCM,data:Is2TG5ZFDv9TowPez7Y7RZ/nrHv8q3SC/lETrcu736o3+xqkTJnorvX+GZsZZBN1gg==,iv:/jZu7mAseCOgqoVpGBr58l5sZSFXDO5S3o2x2xrL4So=,tag:ngLCF+HHf/Gxtbpqy2WcTA==,type:str]
    DATABASE_URL: ENC[AES256_GCM,data:B7j0MWwe4Bt4MB7J4KowN8CAOmgNsqm/0UWykbh0VMDHa/VpA88IanyG9+iTF1k2EqXqVMP0/UhYZB2jzTPXLIvvNdfSNDUXkksX90MsA9nlbqsHuN+hzBCBh4RdGZNiEoM6kyF8p1aSlW84SxnrbnYMJss7,iv:rUAi0YWVNGM6re37XERk8QOUSLyY680/TJllsTBF6jI=,tag:4dyNxrs8eLJgnDNyu4LmkA==,type:str]
    AFFINE_INDEXER_ENABLED: ENC[AES256_GCM,data:XPP3Hd0=,iv:i7cJILY7vzCwpuW8tS/KCY17JrBzAOuUO3oIAU01WtI=,tag:hQcLl6vWGbjVPmFyNXt+vg==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: affine-configuration
    namespace: other-webapps
    labels:
        reconcile.fluxcd.io/watch: Enabled
sops:
    lastmodified: "2026-01-05T04:13:45Z"
    mac: ENC[AES256_GCM,data:tXwu2CE3LEZ5OATzKJURkpel3CGcgBZRNryoWuP/HL20AeXr1ehJOPr2+q7/YTsYMaV8DhJFZWblEPlbTCb0TzRKrmUZVVoe07MV3/dV42pkW712fmnL1u3IxL57uy45FRVDXz0pL2IgLBRNU7xJ3PGqXyT94IlX1syxbD+P4mI=,iv:hsdg5CrnLmw7v5+WtOgXMFk+Y6I+h/B5bTefNz0nKt4=,tag:igl8a8bAwPep4SLOAj5oqQ==,type:str]
    pgp:
        - created_at: "2025-12-19T04:32:28Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4D3ufNC3rOtvoSAQdAeIn2wnFe2gKhZrIZzr3YdFQbcs7aVDRzUEifzCqQ+k8w
            BKa5h91ElcVbbJ8uYlj0CP+vq3iVgfXmJL1dQA/NgLusHzVPAPHpmoFaJQbUXqbw
            0l4BEFn/ZcxKIV605tuu07/sGVnOxUyV8jVWpmLNR93spUQwoA3WqFM7JIiRTbim
            zP+RMxZGsjTprVzjIf7mcW+s2VIh9eTi56T4zo23RMsrqeg1J4u2TGo2T9L+tiNu
            =+iqw
            -----END PGP MESSAGE-----
          fp: 910E6AB3B6B93104BC0D0F5AD48349BEF211483F
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
