apiVersion: v1
stringData:
    POSTGRES_USER: ENC[AES256_GCM,data:S7VW8cbL,iv:zcjwX1Pqz5XuwW0w2YuIL7M4lGOplcI46WmP8WSzoWA=,tag:Mlc28fx7eFt0QfyKIY6hAw==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:x5K0JAvwHr8adTXY4JcT9TRPIF/X/C1MT+r5c9YsWFM=,iv:TVAMa0QLa8MRlD00w4IoFG6wIxQIp8qzeiixaFCZr9U=,tag:hHwK2XYWuG1mq3tOTXuzXA==,type:str]
    POSTGRES_DB: ENC[AES256_GCM,data:tN7kBu27,iv:jrWSAMoPU5i1QvlgILHl5EXamUrxzhtcoH5t7sQMXpY=,tag:n6V+p5xn99Aok07spvbsHQ==,type:str]
    POSTGRES_INITDB_ARGS: ENC[AES256_GCM,data:ZTAwJaEmLwsh+bzumBsgCg==,iv:VJWy2ggauS5K8EIK+kwFLcQVf2D/S97F/MpBTZrES44=,tag:lV1CEMMiwwuFmm16M84ILg==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: affine-postgres-configuration
    namespace: other-webapps
    labels:
        reconcile.fluxcd.io/watch: Enabled
sops:
    lastmodified: "2026-01-05T03:50:36Z"
    mac: ENC[AES256_GCM,data:2QrWmXAWGOYa/kuHVcptax4l2Ho3nukga15j9tI6UgBcbdl0JABBzVy05IkI9u4nmbjuoxiKJfMKWJmQVsKiK1Nriaigh0asb+YX9HdkoPspZ/8CTQmb5ZMAaDwX4l/iOMyfo9nTX0pHBu3rijKVZSWL/2xBvDGiW82qQfQWgjs=,iv:ViV2K0rUq0wKCcHYXRd3E7UcSM3lYE2bKJFVTMqom00=,tag:PM24o5glBfZ4aPTJPT7y5g==,type:str]
    pgp:
        - created_at: "2025-12-19T04:32:28Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4D3ufNC3rOtvoSAQdAeIn2wnFe2gKhZrIZzr3YdFQbcs7aVDRzUEifzCqQ+k8w
            BKa5h91ElcVbbJ8uYlj0CP+vq3iVgfXmJL1dQA/NgLusHzVPAPHpmoFaJQbUXqbw
            0l4BEFn/ZcxKIV605tuu07/sGVnOxUyV8jVWpmLNR93spUQwoA3WqFM7JIiRTbim
            zP+RMxZGsjTprVzjIf7mcW+s2VIh9eTi56T4zo23RMsrqeg1J4u2TGo2T9L+tiNu
            =+iqw
            -----END PGP MESSAGE-----
          fp: 910E6AB3B6B93104BC0D0F5AD48349BEF211483F
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
