apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: affine
  namespace: other-webapps
spec:
  interval: 5m
  upgrade:
    force: true
  chart:
    spec:
      chart: app-template
      version: 4.5.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      interval: 5m
  dependsOn:
    - name: affine-deps
      namespace: other-webapps
  values:
    controllers:
      app:
        enabled: true
        initContainers:
          affine-migration:
            image:
              repository: ghcr.io/toeverything/affine
              tag: stable
            env:
              REDIS_SERVER_HOST: redis
              AFFINE_INDEXER_ENABLED: "false"
              DATABASE_URL: "postgresql://$(DB_USERNAME):$(DB_PASSWORD)@postgres:5432/$(DB_DATABASE)"
            envFrom:
              - secretRef:
                  name: affine-env
            command:
              - sh
              - -c
              - "node ./scripts/self-host-predeploy.js"
        containers:
          app:
            image:
              repository: ghcr.io/toeverything/affine
              tag: stable
            envFrom:
              - secret: affine-configuration
    service:
      app:
        enabled: true
        controller: app
        primary: true
        ports:
          http:
            port: 3010
    ingress:
      app:
        enabled: true
        hosts:
          - host: notes.tam.land
            paths:
              - path: /
                pathType: Prefix
                service:
                  identifier: app
        tls:
          - secretName: tamland-tls
            hosts:
              - notes.tam.land
    persistence:
      config:
        enabled: true
        type: nfs
        server: nfs.local.tam.land
        path: /nfs-share/other-webapps/affine/config
        advancedMounts:
          app:
            app:
              - path: /root/.affine/config
            affine-migration:
              - path: /root/.affine/config
      storage:
        enabled: true
        type: nfs
        server: nfs.local.tam.land
        path: /nfs-share/other-webapps/affine/storage
        advancedMounts:
          app:
            app:
              - path: /root/.affine/storage
            affine-migration:
              - path: /root/.affine/storage
