apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - affine-configuration-secret.sops.yaml
  - affine-postgres-configuration-secret.sops.yaml
  - deps-helm-release.yaml
  - helm-release.yaml
  - persistence.yaml
