apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: affine-postgres
  namespace: other-webapps
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: proxmox-data-ssd-array
  resources:
    requests:
      storage: 50Gi