apiVersion: v1
stringData:
    key: ENC[AES256_GCM,data:5LUY4iEllG4vLlxy1/1waq/lGwY9cv0pbptnRJOksHq4yzJdtgodVgRuyhiKqERL5QWhWx5rrc83ercipBfCffOnjH1/10/pb1dOxCRi63A9I8TvFDAX6mNsGKEaV2CY5sMMJX56CKab8S0HGW1TBiXb6nmKKoUdP6VMTONk97davG4oXJCT4WJMpdmKtHS8nTgYp4w=,iv:mo61eYgeUQDiuioV0as7GoL/bPSiQgHFbl6nMuJHpLg=,tag:kbPcFnKWSbE+3GfYXiqQsA==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: chia-secrets
    namespace: chia
    labels:
        reconcile.fluxcd.io/watch: Enabled
sops:
    lastmodified: "2026-01-04T01:05:29Z"
    mac: ENC[AES256_GCM,data:Ws0YhB0JLYMnKtMEvGB/mgk4r5vqtuJg3/9glCBNO+aXHd246uQRKl3CWm+HmJu7cEhv0FT89m/AKKhvaw94jSivUnpVG/mR90TOzlXODchHY4kPDupvFpZzKlMZ6gQtWe7VdpfUaeeRxTAkXJQovTYyU2KRtmlWBPapme/uMQo=,iv:3MF8DeoTNl1DxDO+K6mzkvfJLUegRU3JvBGrd4nN9ro=,tag:W3lEIg7CtFyWBfTSWoF4Uw==,type:str]
    pgp:
        - created_at: "2025-12-19T04:32:28Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4D3ufNC3rOtvoSAQdAeIn2wnFe2gKhZrIZzr3YdFQbcs7aVDRzUEifzCqQ+k8w
            BKa5h91ElcVbbJ8uYlj0CP+vq3iVgfXmJL1dQA/NgLusHzVPAPHpmoFaJQbUXqbw
            0l4BEFn/ZcxKIV605tuu07/sGVnOxUyV8jVWpmLNR93spUQwoA3WqFM7JIiRTbim
            zP+RMxZGsjTprVzjIf7mcW+s2VIh9eTi56T4zo23RMsrqeg1J4u2TGo2T9L+tiNu
            =+iqw
            -----END PGP MESSAGE-----
          fp: 910E6AB3B6B93104BC0D0F5AD48349BEF211483F
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
