apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: homeassistant
  namespace: smart-home
spec:
  interval: 5m
  driftDetection:
    mode: enabled
  upgrade:
    force: true
  chart:
    spec:
      chart: app-template
      version: 4.5.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      interval: 5m
  values:
    controllers:
      app:
        enabled: true
        containers:
          app:
            image:
              repository: homeassistant/home-assistant
              tag: "2025.12.5"
            env:
              TZ: America/Toronto
              PYTHONPATH: /config/deps
#            Just gunna leave this here.
#            If the module install failure bug pops up, uncomment this and remove PYTHONPATH
#            https://github.com/home-assistant/core/issues/127966#issuecomment-2468391662
#            lifecycle:
#              postStart:
#                exec:
#                  command: ["touch", "/.dockerenv"]
      postgres:
        enabled: true
        pod:
          affinity:
            nodeAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                nodeSelectorTerms:
                  - matchExpressions:
                      - key: extensions.talos.dev/qemu-guest-agent
                        operator: Exists
        containers:
          postgres:
            image:
              repository: postgres
              tag: 18.1
            env:
              PGDATA: /var/lib/postgresql/18/docker/pgdata
            envFrom:
              - secret: homeassistant-postgres-configuration
      influxdb:
        enabled: true
        containers:
          influxdb:
            image:
              repository: influxdb
              tag: 2.8.0
    service:
      app:
        enabled: true
        controller: app
        primary: true
        ports:
          http:
            port: 8123
      postgres:
        enabled: true
        controller: postgres
        ports:
          http:
            port: 5432
      influxdb:
        enabled: true
        controller: influxdb
        ports:
          http:
            port: 8086
    ingress:
      app:
        enabled: true
        hosts:
          - host: "hass.tam.land"
            paths:
              - path: /
                pathType: Prefix
                service:
                  identifier: app
        tls:
          - secretName: tamland-tls
            hosts:
                - hass.tam.land
    persistence:
      appconfig:
        enabled: true
        type: nfs
        server: nfs.local.tam.land
        path: /nfs-share/smart-home/home-assistant/app
        advancedMounts:
          app:
            app:
              - path: /config
                readOnly: false
      llmvision:
        enabled: true
        type: emptyDir
        advancedMounts:
          app:
            app:
              - path: /media/llmvision
                readOnly: false
      pgdata:
        enabled: true
        type: persistentVolumeClaim
        existingClaim: homeassistant-postgres
        advancedMounts:
          postgres:
            postgres:
              - path: /var/lib/postgresql/18/docker
                readOnly: false
      influxconfig:
        enabled: true
        type: nfs
        server: nfs.local.tam.land
        path: /nfs-share/smart-home/influxdb/config
        advancedMounts:
          influxdb:
            influxdb:
              - path: /etc/influxdb2
                readOnly: false
      influxdata:
        enabled: true
        type: nfs
        server: nfs.local.tam.land
        path: /nfs-share/smart-home/influxdb/data
        advancedMounts:
          influxdb:
            influxdb:
              - path: /var/lib/influxdb2
                readOnly: false
