apiVersion: v1
stringData:
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:i9Ip8mhOoE6QhLYWbWQyfzo0D1dczmxRyE5447GGI4g=,iv:kfLVzNvm7uKY/ybAOG8Qe0R399abnvy3XRZFpQrOMpg=,tag:9UQ1i1jp17+qKSBd4YJXXQ==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: homeassistant-postgres-configuration
    namespace: smart-home
    labels:
        reconcile.fluxcd.io/watch: Enabled
sops:
    lastmodified: "2026-01-04T05:42:27Z"
    mac: ENC[AES256_GCM,data:llW8oqUsTtVrnEkr6udJJ1BhUfvNVxym4X/Xb8bTfzqaC6Y2tv9FOH8giwzG5bxgghblfyE1H9eMcwxYiqF96NhXlUBsENx5R0Vr/IDwIkQ90UUG7HnNvc7SA5UkG4ZAEBvNWIIHbBoKl4Pks9HCRFn2wftXeUCkm2swxNJTSIo=,iv:s5Cr0ScBiTjhW/vXIWwHsnI6Tex0yc8P76BftbxIpqo=,tag:KDCwXCjnBkrx6FllFIwwkA==,type:str]
    pgp:
        - created_at: "2025-12-28T23:05:12Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4D3ufNC3rOtvoSAQdAVINNFpAL2iS66cFDAhjfsCak7k9nBCw1oR9Y9x4ndlsw
            uzAZ9o/WKujYRei3TglDgIOhW/3ITLBdxx/z2neZI9136voEIPiKG+AP4MgR4Wqa
            0l4BVjTypitdAMe5EMdjVI+4Bb4dGrGWwia6RcQBriF9ZDK+uSmTm1b3tcn3GCuy
            USmKARGaPY/dYZPqG9x+xMwXORdAD55laTbuYrZ/AqK5Nql5TSmhL7/DHZ6O/4Nt
            =LF6e
            -----END PGP MESSAGE-----
          fp: 910E6AB3B6B93104BC0D0F5AD48349BEF211483F
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
