apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: homeassistant-postgres
  namespace: smart-home
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: proxmox-data-ssd-array
  resources:
    requests:
      storage: 100Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: homeassistant-influxdb
  namespace: smart-home
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: proxmox-data-ssd-array
  resources:
    requests:
      storage: 100Gi