apiVersion: v1
stringData:
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:i9Ip8mhOoE6QhLYWbWQyfzo0D1dczmxRyE5447GGI4g=,iv:kfLVzNvm7uKY/ybAOG8Qe0R399abnvy3XRZFpQrOMpg=,tag:9UQ1i1jp17+qKSBd4YJXXQ==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: homeassistant-postgres-sops-secret
    namespace: smart-home
    labels:
        reconcile.fluxcd.io/watch: Enabled
sops:
    lastmodified: "2025-12-28T23:14:32Z"
    mac: ENC[AES256_GCM,data:yCLU13YUThKJZoJSt+ve96FSHU8V+58yBuPtoZZzVqvvz2K4LtbjdAaVFigm8A0Edu5mVoGa9y9mY1agMs2ueIuOPMqZZ7dUeGGI38vMUwFA3m1u6NPiDkBoWdXkHsfoL9r/R1Ap0v8HufV7c0tFb+klcuyDf9ot9hE0scHEggo=,iv:4Mf6CP8viXGUr+Ayl6hAb90mkmVVGogd8JzhV1rmuAI=,tag:uirau+V8i1qQzQzMW1+ekA==,type:str]
    pgp:
        - created_at: "2025-12-28T23:05:12Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4D3ufNC3rOtvoSAQdAVINNFpAL2iS66cFDAhjfsCak7k9nBCw1oR9Y9x4ndlsw
            uzAZ9o/WKujYRei3TglDgIOhW/3ITLBdxx/z2neZI9136voEIPiKG+AP4MgR4Wqa
            0l4BVjTypitdAMe5EMdjVI+4Bb4dGrGWwia6RcQBriF9ZDK+uSmTm1b3tcn3GCuy
            USmKARGaPY/dYZPqG9x+xMwXORdAD55laTbuYrZ/AqK5Nql5TSmhL7/DHZ6O/4Nt
            =LF6e
            -----END PGP MESSAGE-----
          fp: 910E6AB3B6B93104BC0D0F5AD48349BEF211483F
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
