apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nvidia-device-plugin
  namespace: nvidia
spec:
  interval: 5m
  upgrade:
    force: true
  chart:
    spec:
      chart: nvidia-device-plugin
      version: 0.18.2
      sourceRef:
        kind: HelmRepository
        name: nvidia-k8s-device-plugin
        namespace: flux-system
      interval: 5m
  values:
    runtimeClassName: nvidia
    cdi:
      enabled: true
    dcgmExporter:
      enabled: false
    driver:
      enabled: false
    nfd:
      enabled: true
    toolkit:
      enabled: false
