apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: wyoming
  namespace: smart-home
spec:
  interval: 5m
  upgrade:
    force: true
  chart:
    spec:
      chart: app-template
      version: 4.6.2
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      interval: 5m
  values:
    controllers:
      whisper:
        enabled: true
        containers:
          app:
            image:
              repository: lscr.io/linuxserver/faster-whisper
              tag: 3.1.0
            env:
              PUID: 568
              GUID: 568
              TZ: America/Toronto
              WHISPER_MODEL: base.en
              WHISPER_LANG: en
      piper:
        enabled: true
        containers:
          app:
            image:
              repository: lscr.io/linuxserver/piper
              tag: 2.2.2
            env:
              PUID: 568
              GUID: 568
              TZ: America/Toronto
              PIPER_VOICE: en_US-lessac-medium
      openwakeword:
        enabled: true
        containers:
          app:
            image:
              repository: rhasspy/wyoming-openwakeword
              tag: 2.1.0
    service:
      whisper:
        enabled: true
        controller: whisper
        primary: true
        ports:
          http:
            port: 10300
      piper:
        enabled: true
        controller: piper
        primary: true
        ports:
          http:
            port: 10200
      openwakeword:
        enabled: true
        controller: openwakeword
        primary: true
        ports:
          http:
            port: 10400
    persistence:
      config:
        enabled: true
        type: nfs
        server: nfs.local.tam.land
        path: /nfs-share/smart-home/wyoming/whisper
        advancedMounts:
          whisper:
            app:
              - path: /config
      piper-config:
        enabled: true
        type: nfs
        server: nfs.local.tam.land
        path: /nfs-share/smart-home/wyoming/piper
        advancedMounts:
          piper:
            app:
              - path: /config
