apiVersion: v1
stringData:
    values.yaml: ENC[AES256_GCM,data:IPhSa46Z7QBp/c5w+lBPjkHKNdjUmzXNDA0CjLizpGu4xp3wQUWQCWNQLhTNvc2rfsp2xt08ztx2jBbwoHTb/gxv8C6oR/ADCD8BxdfGElGaoDXswh0csqnVykGykeDNXEkivISeXCn9jA88t8MiGsPPPhRyVRy9L3snjc6xzMEbXTJl5+S9RMP5qJfeQKv0qPCszinDgQ+6ULibYTUTBZ2LBBnlDQ4wD9TJfW7Tv+PASyCm74mSC2VQrtZ4kJauItQRvg==,iv:4EoiC8+vOmS8jQQ+eH+6+FXheCHhdtcqRZKB2fxXmy0=,tag:P8jRiUG8ZiET0FFaVonSBA==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: proxmox-csi-sops-secrets
    namespace: csi-proxmox
    labels:
        reconcile.fluxcd.io/watch: Enabled
sops:
    lastmodified: "2026-01-03T05:31:22Z"
    mac: ENC[AES256_GCM,data:hKpzXH4BnSR6okAWkN6G/LaRapioDh+4wcxEIspxSz4Uw+oyAoSMG/sCybHjRfG2uZs6Igg0bhAk26ZjociUhicnKnTojfq6My3gCgjjaEphL0YiCFz896hK90q1SF34CtgslS64NM6gJx9crGg4QlpuYV6iF6JFwbD5ywnkJzs=,iv:E87QwY8mO6Phbm/NDfwFCjxnG7wSCgFyNNCqqTuev/c=,tag:ITVjJqp8nmWPBiEM3sah5w==,type:str]
    pgp:
        - created_at: "2025-12-19T04:32:28Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4D3ufNC3rOtvoSAQdAeIn2wnFe2gKhZrIZzr3YdFQbcs7aVDRzUEifzCqQ+k8w
            BKa5h91ElcVbbJ8uYlj0CP+vq3iVgfXmJL1dQA/NgLusHzVPAPHpmoFaJQbUXqbw
            0l4BEFn/ZcxKIV605tuu07/sGVnOxUyV8jVWpmLNR93spUQwoA3WqFM7JIiRTbim
            zP+RMxZGsjTprVzjIf7mcW+s2VIh9eTi56T4zo23RMsrqeg1J4u2TGo2T9L+tiNu
            =+iqw
            -----END PGP MESSAGE-----
          fp: 910E6AB3B6B93104BC0D0F5AD48349BEF211483F
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
