apiVersion: v1
stringData:
    PAPERLESS_CONSUMER_POLLING: ENC[AES256_GCM,data:Yqg=,iv:CRwdYj++4tMQP7loKDLPkN1j9EV/LZeO6e5Cy3wMPr4=,tag:xgTvAPzywpVFgHQoQbXqjg==,type:int]
    PAPERLESS_DBHOST: ENC[AES256_GCM,data:ehTkhppqroeY1XPPRnnqFEQdh13muEJjLQJBma11JS/R0uDZWbObq53a3cztlfYJm75kQJo7,iv:8tBXBPr+fmz9NrhF0pBMI7bzQUJniJj9HnI8UVFWMTA=,tag:woTGji7I6/hYmwjMupkXDg==,type:str]
    PAPERLESS_DBNAME: ENC[AES256_GCM,data:2mlIU0tGh5ZA,iv:5ogLTT2e0gjxGNqje7Ilh+mwatVkvc3NybXs6sKXQPs=,tag:GHmMsz5CinREknxV5joLcw==,type:str]
    PAPERLESS_DBPASS: ENC[AES256_GCM,data:U9aId8oX/9iTfWrt/MkZPDvwOJVY4KnkyEQrQE6OqJU=,iv:I9JlBRNErj1VQ4Cr7tgQgFJSk4YtrCV5YsmQO7QC5rQ=,tag:wf5vrW3vsfC38EOnnaYh6g==,type:str]
    PAPERLESS_DBUSER: ENC[AES256_GCM,data:ZNShYBmtttoI,iv:XF84rRNrYJxxGN8oWiF6n4yFL1T0zwoF3Hm9XryAwMA=,tag:WloXiqafhLgyWG5218gkgg==,type:str]
    PAPERLESS_OCR_LANGUAGE: ENC[AES256_GCM,data:3oSx,iv:MqiG5cRP7a5Gk/4Ca2gXfGbyGRLN51fs6WFUPOk8yic=,tag:iwGpNjwNmFOmj/Xibn00Fw==,type:str]
    PAPERLESS_REDIS: ENC[AES256_GCM,data:4JORKj9ce++IALbXTYEsQ4SnQQgJiOFKF4K4GFQ8MvIUYxFfRmduLkmngPn+Cc1jDU11MIhtVQ5hZfAC6rX1/Q==,iv:DSq3WaUOPr0KHvPKmVdeGt8qbe8nyYvNLhhrqjsZyjk=,tag:U6KyCFtIUDWw1LkkSu9ChQ==,type:str]
    PAPERLESS_SECRET_KEY: ENC[AES256_GCM,data:8BnAcq2pEK87NQP1I97ADKCz3n5q67Bpex1FGbQTH+8=,iv:X8T3m2eXOqkADkCetqJGKwvvIh0fI58VrIGQnFK41OU=,tag:GQxmhtfS1Fw6XNYUZoEiBw==,type:str]
    PAPERLESS_TIME_ZONE: ENC[AES256_GCM,data:kuxZdo8kLuzsFDIgm6mc,iv:Ml4aggd89ksoVXb/Ca6XKG8BnvgJo+IQZ8+g/IoCb6Y=,tag:xZY5KXcEc2FQFrdFDd7U1w==,type:str]
    PAPERLESS_URL: ENC[AES256_GCM,data:Rn7a8wqq17fA3YXn78tU34KYyw9d6tSceh37+LTh1H0=,iv:Ec7/YRW7j1ashuEqNtyMOeK+8rj+UBxxiG5KYNPNIhg=,tag:LhRevJ/aY3sgL7jO/Ee+ow==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:I+8dvZn6EgkvEgaicT968vCW161aKJOv0OEbYspkYOM=,iv:KfAOR2OZXV6LtpAYCsSetOrZI0gspGf6bof6oqUPwnc=,tag:SRDaqZWfeMAWVSzm9mX/lg==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: paperless-configuration
    namespace: other-webapps
    labels:
        reconcile.fluxcd.io/watch: Enabled
sops:
    lastmodified: "2026-01-04T02:52:22Z"
    mac: ENC[AES256_GCM,data:monb321XFnlONo0rgZQM7fOigVwGqUrLECMuLF78ddP1XxssF+geNtoQO7EOWtiGi5RLNbMwRoFUJa3A0YqcVhgsIzDgkQm6NYg1zo6fk4wVADyOHHI+Aqvg5I+DvkuSmWsuLX1icv4df8tqg7MP4au4DByazGoJBxC/rWBvSAc=,iv:BgGyevPp5v9ywwpdltnPV+LnZp+VFLcmAtle91xtaTo=,tag:FCgMmHDUK8/LwiRWQ9CC+Q==,type:str]
    pgp:
        - created_at: "2025-12-19T04:32:28Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4D3ufNC3rOtvoSAQdAeIn2wnFe2gKhZrIZzr3YdFQbcs7aVDRzUEifzCqQ+k8w
            BKa5h91ElcVbbJ8uYlj0CP+vq3iVgfXmJL1dQA/NgLusHzVPAPHpmoFaJQbUXqbw
            0l4BEFn/ZcxKIV605tuu07/sGVnOxUyV8jVWpmLNR93spUQwoA3WqFM7JIiRTbim
            zP+RMxZGsjTprVzjIf7mcW+s2VIh9eTi56T4zo23RMsrqeg1J4u2TGo2T9L+tiNu
            =+iqw
            -----END PGP MESSAGE-----
          fp: 910E6AB3B6B93104BC0D0F5AD48349BEF211483F
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
