apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ollama
  namespace: other-webapps
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-fast-960-worker06
  resources:
    requests:
      storage: 50Gi