apiVersion: v1
stringData:
    cloudflare-api-key: ENC[AES256_GCM,data:VmPrDfSA0w8cUae38F4G4sOHhkNr5Jie+2ReKxu+EgG8OaUGc5wtMA==,iv:7p58G6k7aqVeqJn2JA4/0GhfF+VECdpDcPHbmizFXhQ=,tag:v0qVIKaV7j0m7f+CdKqbnA==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: cloudlare-api-secret
    namespace: cert-manager
    labels:
        reconcile.fluxcd.io/watch: Enabled
sops:
    lastmodified: "2026-01-03T20:44:49Z"
    mac: ENC[AES256_GCM,data:+MDMDW0/S8BNezh42nizBWwpUp1J21jLB974AqNiCU8RcLsupbKE+y7cbcQB2HCRbmvyiirIov1Vb27LCYWXRhq18fpMzzVTzAjPc64CbYGGF5suginDefIuSQ3snCtkA1S25xMrQNoxEedkASHPDNQr3wfEMIzinXuU6QrxlTQ=,iv:N3oaT23YslCoRCEX8d3Qe5m1qTElRo5RV7zc6Csh3TE=,tag:d2Z/xDgB5TT5NYZBRPifpg==,type:str]
    pgp:
        - created_at: "2025-12-19T04:32:28Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4D3ufNC3rOtvoSAQdAeIn2wnFe2gKhZrIZzr3YdFQbcs7aVDRzUEifzCqQ+k8w
            BKa5h91ElcVbbJ8uYlj0CP+vq3iVgfXmJL1dQA/NgLusHzVPAPHpmoFaJQbUXqbw
            0l4BEFn/ZcxKIV605tuu07/sGVnOxUyV8jVWpmLNR93spUQwoA3WqFM7JIiRTbim
            zP+RMxZGsjTprVzjIf7mcW+s2VIh9eTi56T4zo23RMsrqeg1J4u2TGo2T9L+tiNu
            =+iqw
            -----END PGP MESSAGE-----
          fp: 910E6AB3B6B93104BC0D0F5AD48349BEF211483F
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
