apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - affine
  - ghostfolio
  - homepage
  - immich
  - lubelog
  - ollama
  - radicale
  - stirlingpdf
  - vaultwarden