apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: local-path-provisioner-worker06
  namespace: local-path-provisioner
spec:
  interval: 30m
  upgrade:
    force: true
    cleanupOnFail: true
  chart:
    spec:
      chart: ./deploy/chart/local-path-provisioner
      sourceRef:
        kind: GitRepository
        name: local-path-provisioner
        namespace: flux-system
      interval: 30m
  values:
    nodeSelector:
      kubernetes.io/hostname: worker06
    storageClass:
      create: true
      name: local-fast-960-worker06
      defaultClass: false
      defaultVolumeType: hostPath
      reclaimPolicy: Delete
      volumeBindingMode: WaitForFirstConsumer
    nodePathMap:
      - node: worker06
        paths:
          - /var/mnt/fast-960
      - node: DEFAULT_PATH_FOR_NON_LISTED_NODES
        paths: []