apiVersion: v1
stringData:
    DATABASE: ENC[AES256_GCM,data:OuFYU+Bf,iv:HZeAQu8xP2I4B/0xd3+aIpoPSvHbgoIn2k9t7YoAodI=,tag:YKmCD+OehhroAA9DbCPHmQ==,type:str]
    HOSTNAME: ENC[AES256_GCM,data:TpsmXWR8+r4Cio9Yg2fpwTocrt/Ev4bQCgzaO/H9kCzq3oquNE8GgWnIjvg=,iv:+yH7CbYv/Xcz5wn/VZbt/VD4W8FCJzZ3fVyJbdTio0s=,tag:n1iaqmSemmjrv658zvkuAw==,type:str]
    PASSWORD: ENC[AES256_GCM,data:ax3U2QZdTnG1s5v/+vIsvWD21ozX1YhMol3OvRNp+2c=,iv:Rhv8lcr2nsUF4M6ow0kOkev1Hnmvw3N90mSpqeSrD8s=,tag:74rYSpks1b3va1m7UITUyw==,type:str]
    PORT: ENC[AES256_GCM,data:+zc6SA==,iv:u2BVili6Xqwjqo3u668jpZGEtzijZPINCKMcgmsDagc=,tag:QN2S/d/lFJ5QXm8u0Sh+xA==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:wyi0eOmsO7oJaWju8GSBNKzQ8WvE+qjhPT414eoeR+4=,iv:fPOtz8Svk26PrF342mZfU/WWBTl0VQKzxUIHETOqlOA=,tag:jPwoizQgoY8cvgyz5gMu/g==,type:str]
    USERNAME: ENC[AES256_GCM,data:JbGgbt1U,iv:u3r1HdlsrTtpdI9j4ExuOKExS0JQVocik3BA1oIJy7o=,tag:L2G9xp7UT+IrJlAkRPdwIA==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: zabbix-postgres-configuration
    namespace: monitoring
    labels:
        reconcile.fluxcd.io/watch: Enabled
sops:
    lastmodified: "2026-01-05T02:55:07Z"
    mac: ENC[AES256_GCM,data:PcO/Dg8dBMmd1DoLqtC1e+3OpFU+GJzp/H1d2Vo6KcWy1c3EteQDHUPcvf6otSuYk80tKlQdQ3w9Idb7X0MjmOVCiePuLtLrKs6EFQMdTR4g0vdIacsIgWyyTyW4feQL/F86QVxyvFbN5dJsXcWoEAEhDQ0KEyxiux3GqGtDXSg=,iv:t2rw4MNRPRULdMWTLRx2kA/EQTL6aizP3nS/U8oqB7Q=,tag:/2mM+2jtzKG1Q0hv3OnidQ==,type:str]
    pgp:
        - created_at: "2025-12-19T04:32:28Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4D3ufNC3rOtvoSAQdAeIn2wnFe2gKhZrIZzr3YdFQbcs7aVDRzUEifzCqQ+k8w
            BKa5h91ElcVbbJ8uYlj0CP+vq3iVgfXmJL1dQA/NgLusHzVPAPHpmoFaJQbUXqbw
            0l4BEFn/ZcxKIV605tuu07/sGVnOxUyV8jVWpmLNR93spUQwoA3WqFM7JIiRTbim
            zP+RMxZGsjTprVzjIf7mcW+s2VIh9eTi56T4zo23RMsrqeg1J4u2TGo2T9L+tiNu
            =+iqw
            -----END PGP MESSAGE-----
          fp: 910E6AB3B6B93104BC0D0F5AD48349BEF211483F
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
