apiVersion: v1
stringData:
    username: ENC[AES256_GCM,data:1eYdMA==,iv:wQbO+C7TVpCw7XUtvm7d+RrqCT3YxUvsiSMMpEsSXoc=,tag:ooWatTkCfCOPDVcZQd6GnQ==,type:str]
    token: ENC[AES256_GCM,data:KCLNDZmcdqJgmluDjTbZGyqSb9/GTcfzV2b1Jv2b,iv:KLS6rcwyw1YUbtF6ItXycK94f0Epc/l21lqQ4My6L1Y=,tag:9NPv7BG+bY0c3QJ9r9G8cA==,type:str]
    game_password: ENC[AES256_GCM,data:ZU4ieg8=,iv:rbHM/BSQ5yVqUoaDXvZooPAkh4Mb6MrzHKZ/wKpzZN8=,tag:Tks4MdW4rSFuMVjqTSRjBQ==,type:str]
    rconpw: ENC[AES256_GCM,data:6i9wjBErkul5kDbHiXaw,iv:VTvBNvZkBP9gS2SX56bXOnjdNH7fvQeHo23TCv8EgQw=,tag:QdKJbtc4DrVCu8o8w9uG5w==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: factorio-sops-secret
    namespace: smart-home
    labels:
        reconcile.fluxcd.io/watch: Enabled
sops:
    lastmodified: "2025-12-29T04:14:22Z"
    mac: ENC[AES256_GCM,data:Uk91LWFaqcApnXbGgwqJvrmzDp/B0EdTFGl6jEyykIadJ2U8IJTrAe/ClUw6UGmzaE9L3oQi0mHFElj0YdKQTxy51igF1ZPFLQXO5vZ541WmLg6aCL3OCD1P0OuWo2krDAfHXQ1T7lWLdmhdsILsLiMKAWY5pA5wJj8kHqH80I0=,iv:bLF7mui9jH0ihP2CMzwQF17CM5LEQmH+BGpe7pUV+GI=,tag:QLUo9AUsRR5VyYT1fk6KZg==,type:str]
    pgp:
        - created_at: "2025-12-28T23:05:12Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4D3ufNC3rOtvoSAQdAVINNFpAL2iS66cFDAhjfsCak7k9nBCw1oR9Y9x4ndlsw
            uzAZ9o/WKujYRei3TglDgIOhW/3ITLBdxx/z2neZI9136voEIPiKG+AP4MgR4Wqa
            0l4BVjTypitdAMe5EMdjVI+4Bb4dGrGWwia6RcQBriF9ZDK+uSmTm1b3tcn3GCuy
            USmKARGaPY/dYZPqG9x+xMwXORdAD55laTbuYrZ/AqK5Nql5TSmhL7/DHZ6O/4Nt
            =LF6e
            -----END PGP MESSAGE-----
          fp: 910E6AB3B6B93104BC0D0F5AD48349BEF211483F
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
