apiVersion: 'kubernetes-client.io/v1'
kind: ExternalSecret
metadata:
  name: qbittorrent-configuration
  namespace: media
spec:
  backendType: vault
  vaultMountPoint: kubernetes
  vaultRole: external-secrets-role
  dataFrom:
    - secrets/data/media/qbittorrent
