apiVersion: v1
stringData:
    WIREGUARD_PRIVATE_KEY: ENC[AES256_GCM,data:dM1beiX9SYv0SUQ8niQ6d65PVdBctQ9IWi1oju+4E4UyLK+xW22AGXdOA+M=,iv:c5A5QzBae5EZ11zx7+a+SPRQrT85GbHcFl5k5S4X9Oo=,tag:sC36kw8aGOdy/AX/xFXg2w==,type:str]
    WIREGUARD_ADDRESSES: ENC[AES256_GCM,data:f5xjlFpar0g6EyjKo9d+,iv:Q6HKXB+AOPt2Zj81UG0WitdUdLruUzgDSkQ7pFDJ/Uk=,tag:Ii4NRDRdG/gxsO5Sh/OUag==,type:str]
    FIREWALL_INPUT_PORTS: ENC[AES256_GCM,data:X62ejA==,iv:QkgpQmCjX8JPvEuHYGmo5vYoNp0a1wQE2uulY9E1ObY=,tag:4Id1T8wVb0FuSKhbL+odiA==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: qbittorrent-gluetun
    namespace: media
    labels:
        reconcile.fluxcd.io/watch: Enabled
sops:
    lastmodified: "2026-01-11T20:36:20Z"
    mac: ENC[AES256_GCM,data:VvlU6BsU9BSG/lk1sPF6o5usUfstt4ttKceDGqnJ5Ix6E4Ycxi2et8fXgvL/XKuuLtPqUk6DUdY89kKiFyaxxtBlTiP7oLo4nIaTGkuAiSuzU9IG1nTG3zqenfwynCfT12r1+wNsw4TaRVfb3PZa9L+A6cmlSqyBW9lxA16ITUQ=,iv:W7IsaubtrGVERs6A/T/JOCk59z+8N+0uua4/xqvM9zI=,tag:Nk3JC9J0VvrrGePMIXeHtg==,type:str]
    pgp:
        - created_at: "2025-12-19T04:32:28Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4D3ufNC3rOtvoSAQdAeIn2wnFe2gKhZrIZzr3YdFQbcs7aVDRzUEifzCqQ+k8w
            BKa5h91ElcVbbJ8uYlj0CP+vq3iVgfXmJL1dQA/NgLusHzVPAPHpmoFaJQbUXqbw
            0l4BEFn/ZcxKIV605tuu07/sGVnOxUyV8jVWpmLNR93spUQwoA3WqFM7JIiRTbim
            zP+RMxZGsjTprVzjIf7mcW+s2VIh9eTi56T4zo23RMsrqeg1J4u2TGo2T9L+tiNu
            =+iqw
            -----END PGP MESSAGE-----
          fp: 910E6AB3B6B93104BC0D0F5AD48349BEF211483F
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
