apiVersion: v1
stringData:
    WIREGUARD_PRIVATE_KEY: ENC[AES256_GCM,data:dM1beiX9SYv0SUQ8niQ6d65PVdBctQ9IWi1oju+4E4UyLK+xW22AGXdOA+M=,iv:c5A5QzBae5EZ11zx7+a+SPRQrT85GbHcFl5k5S4X9Oo=,tag:sC36kw8aGOdy/AX/xFXg2w==,type:str]
    WIREGUARD_ADDRESSES: ENC[AES256_GCM,data:f5xjlFpar0g6EyjKo9d+,iv:Q6HKXB+AOPt2Zj81UG0WitdUdLruUzgDSkQ7pFDJ/Uk=,tag:Ii4NRDRdG/gxsO5Sh/OUag==,type:str]
    FIREWALL_INPUT_PORTS: ENC[AES256_GCM,data:p9LSWw==,iv:JD14qpSNDYy2wunRVCCtaR6YFrdda3YR+ut9r6rSzUI=,tag:6iqP8q7jYTd5Ra9O6mlYUQ==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: qbittorrent-gluetun
    namespace: media
    labels:
        reconcile.fluxcd.io/watch: Enabled
sops:
    lastmodified: "2026-01-11T20:43:58Z"
    mac: ENC[AES256_GCM,data:nN8qGBrbymJMDuWbrm9CSEA/Lkrsn/jeWZ09dRx2MaiQeyzZEwNH54dKzJTlQUXlS/KHbS/Tx6iDROAn+3X7lerrr5qPxHPf/QGkFpPcpRFED/Ew0wFXYo5cpCPjAaClrK93HaNfEnv0UT8QdjxvsFQeOqgoVagujwLSpjRf1bg=,iv:4n5+vfj2JaOIWffe5/NYnXKbiuGc0sDDzPNqaUS/5rA=,tag:3BKdV2iFirjSDeRpeR/4hQ==,type:str]
    pgp:
        - created_at: "2025-12-19T04:32:28Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4D3ufNC3rOtvoSAQdAeIn2wnFe2gKhZrIZzr3YdFQbcs7aVDRzUEifzCqQ+k8w
            BKa5h91ElcVbbJ8uYlj0CP+vq3iVgfXmJL1dQA/NgLusHzVPAPHpmoFaJQbUXqbw
            0l4BEFn/ZcxKIV605tuu07/sGVnOxUyV8jVWpmLNR93spUQwoA3WqFM7JIiRTbim
            zP+RMxZGsjTprVzjIf7mcW+s2VIh9eTi56T4zo23RMsrqeg1J4u2TGo2T9L+tiNu
            =+iqw
            -----END PGP MESSAGE-----
          fp: 910E6AB3B6B93104BC0D0F5AD48349BEF211483F
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
