apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: frigate-cache
  namespace: smart-home
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-fast
  resources:
    requests:
      storage: 220Gi
  volumeName: pv-fast-240-worker06