apiVersion: v1
stringData:
    WIREGUARD_PRIVATE_KEY: ENC[AES256_GCM,data:UIs31yfVEBLeZtr9z2qhCvzvVAlTKzBPhXXXh2jnJljMRcddk6Jpx2lwO7A=,iv:Aw12OwD5h9nlulvkbYKHkHmouKqhRSMfFjsUukNG/UI=,tag:XxF/v8Hrp8xGhy/5Fwp91w==,type:str]
    WIREGUARD_ADDRESSES: ENC[AES256_GCM,data:hAbcrBZZ3SObHkxbFZJE,iv:p+NsFesTSGmXAU5wEj/lzJKcZBK3EaRyc0hYy5RpmSU=,tag:qW29HF2Ei1+LthP7xhEQ3g==,type:str]
    FIREWALL_INPUT_PORTS: ENC[AES256_GCM,data:YvnLLw==,iv:FFm4pPb+N/prlRiQyuV12S6g7+tl7EhziojQhVZ2Q8s=,tag:v/yfAKB9ksorI/2uketyow==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: prowlarr-gluetun
    namespace: media
    labels:
        reconcile.fluxcd.io/watch: Enabled
sops:
    lastmodified: "2026-01-11T20:59:54Z"
    mac: ENC[AES256_GCM,data:ppx0cX/06lyrQuDgCsvhL1XFSdF7ORi0Ba5LVjoyHNPtFP0jOESKoD0vzd6RHV8xNnifN6BLg5NsWgXlfr8h8lxeucPHhQVdeenHiK+ydMHhgtGziGjpQkGApJbZHSBoE47azctEofmzXkumWWrGOzZWdz6mnUvAY2zcubMeTPE=,iv:UxIIn4X4W/plRC4j69vsAUZFJWHF2qOct4N3u/wQf5M=,tag:3uVyMpz/RgZgGkGpR5Rhug==,type:str]
    pgp:
        - created_at: "2025-12-19T04:32:28Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4D3ufNC3rOtvoSAQdAeIn2wnFe2gKhZrIZzr3YdFQbcs7aVDRzUEifzCqQ+k8w
            BKa5h91ElcVbbJ8uYlj0CP+vq3iVgfXmJL1dQA/NgLusHzVPAPHpmoFaJQbUXqbw
            0l4BEFn/ZcxKIV605tuu07/sGVnOxUyV8jVWpmLNR93spUQwoA3WqFM7JIiRTbim
            zP+RMxZGsjTprVzjIf7mcW+s2VIh9eTi56T4zo23RMsrqeg1J4u2TGo2T9L+tiNu
            =+iqw
            -----END PGP MESSAGE-----
          fp: 910E6AB3B6B93104BC0D0F5AD48349BEF211483F
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
