apiVersion: 'kubernetes-client.io/v1'
kind: ExternalSecret
metadata:
  name: unifi-configuration
  namespace: admin
spec:
  backendType: vault
  vaultMountPoint: kubernetes
  vaultRole: external-secrets-role
  dataFrom:
    - secrets/data/admin/unifi
