apiVersion: v1
stringData:
    MONGO_AUTHSOURCE: ENC[AES256_GCM,data:TxzqscE=,iv:WGbYBXOCer4UlpzUG/STJRHRZJeIT/Zc8TTklbxiKXI=,tag:c0YMieB4wpa3HbVFI8qfHw==,type:str]
    MONGO_DBNAME: ENC[AES256_GCM,data:a1oaqaI=,iv:G4QY3iF8Rv27Y9GLchWZvpQnCqjwPN24NvlRF5XZKIQ=,tag:Uys2Gfrq7BIrhMCIqdsrwg==,type:str]
    MONGO_HOST: ENC[AES256_GCM,data:9MtCOPZxPx2f,iv:WPvviWNA9CrH1k2vqLo77e/KdxDLiZgB4xu8xAGoG/U=,tag:fqbJtWpcRxzpA1j7WXBwcw==,type:str]
    MONGO_INITDB_ROOT_PASSWORD: ENC[AES256_GCM,data:qYI9V6c4o4eh9XUfDn4xBhDV+fB0BmpwA8VrwBVm8wc=,iv:XqyUoUjtIYSHZwZnNtSvn4z4M4a2X9G7YKDJHDiYGEU=,tag:F/4Dm0iKo2SthJzEzizosA==,type:str]
    MONGO_INITDB_ROOT_USERNAME: ENC[AES256_GCM,data:/b2ICw==,iv:/pBk13k+H9yFyZxBZi780Rgl0isR42X+ADac7TlMEro=,tag:tWHUPspdccCMDC+Ayc/LJA==,type:str]
    MONGO_PASS: ENC[AES256_GCM,data:cerMW7HzFax1mRcgkQUHF9b6YPj3wbnje0gLxvtK99E=,iv:zuASoGuxenRzguw+VaFdzupdNQkibjcmust/dWuLQps=,tag:Xj2kECIA/1+Orp0WbUtpVg==,type:str]
    MONGO_PORT: ENC[AES256_GCM,data:jbCFkb4=,iv:oyZxeTj3lZtis/nANhiM1UoTsgM/hnZDaUwh4NpkZFo=,tag:zxDXvbO35H0Cz5axetBBaw==,type:int]
    MONGO_USER: ENC[AES256_GCM,data:4BG3niw=,iv:A8RuzKhlCsv01DtND6qE+5awkJv248JaYP4SOe23TLo=,tag:WQQsmjB049ygR0KNpzXAkQ==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: unifi-configuration
    namespace: admin
    labels:
        reconcile.fluxcd.io/watch: Enabled
sops:
    lastmodified: "2026-01-03T22:37:47Z"
    mac: ENC[AES256_GCM,data:wSaBBz6SO1R6TgLRwXGwqSkdjbNY3dtzArQnEwJtiu6Lr3dWpFdxWfAFHA02EwTMoHrgMTkMoOQT/9S9uEVFSWC7GTZCRi1NoIdiae33JpB8qZTm8EGlKXQiat5ySIt0JPStui7gCl7e5yQLOc6vMhzkrUTwJ9tJMM8ZHykhTw4=,iv:j2hmrGj71o5eOl7wwdUkCJqH4UhU52bDJ1a+ZHkxFOs=,tag:mS+/MfuDoYDHkwJBCUmxqA==,type:str]
    pgp:
        - created_at: "2025-12-19T04:32:28Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4D3ufNC3rOtvoSAQdAeIn2wnFe2gKhZrIZzr3YdFQbcs7aVDRzUEifzCqQ+k8w
            BKa5h91ElcVbbJ8uYlj0CP+vq3iVgfXmJL1dQA/NgLusHzVPAPHpmoFaJQbUXqbw
            0l4BEFn/ZcxKIV605tuu07/sGVnOxUyV8jVWpmLNR93spUQwoA3WqFM7JIiRTbim
            zP+RMxZGsjTprVzjIf7mcW+s2VIh9eTi56T4zo23RMsrqeg1J4u2TGo2T9L+tiNu
            =+iqw
            -----END PGP MESSAGE-----
          fp: 910E6AB3B6B93104BC0D0F5AD48349BEF211483F
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
