apiVersion: v1
stringData:
    config: ENC[AES256_GCM,data:6nOIhc2Oh6HYgeud2858Z7rX3WBMuUXgTjrcUi60HQ7fRBQUvjepg/5wyLxZbvhWEbkB2+wRTfqMipbCIOsNc8cEDSLg18Y1FTnUijZgDTVNAMWPDsKI9RHHgGDK0dkYutmwHX/DtCcKKpqLSGwQSzPpWJDKJquZRIc9x15DZdS0YQ4N01o7WjziyLeyMuLaZb8bJIKdDJNowIFRgiviPm43stwxTSPnOzIX3sg/unLxuJgrewrplIN2fKLN0LH2QeAqHFRK1uEZu2DHI0vLqpi/OvWeZvxddMWhz1+oOQK61IQK/4bfzubUf6iYWidbxQ8gFekdlSBPnWqjWxUWi614RMW88MiNHaK4jR5wcBuoPvUxoPYAACO+ErQqTMgunCsgPgWFj88cQk7QanK0RIFYC5dLrJv2aHrrGCjBEJa4+9JMD+8Au/8rAAu1Pbj4LAob,iv:7BAqeVU3IqwtSmi+OiZcGZRjsgeaHbGOdIciEAVrYh0=,tag:FsLI1TEOLRcVmXDSYLf9DQ==,type:str]
    rights: ENC[AES256_GCM,data:fdMt5/WqODO2S15B9DQiZbhdkqPMoHXwXjbIKtvr1LryrriX4vwdZi10VO84ds7jzHBuGszzt1j3wxFV6bmCBB8svi2xRogBmthBPVyVOvg1UZrecoK1XReBeUFuSKuoGz3IHAEXpbCILnOy1b2es7xuftjcTwSO6X7/sfLQBFR000vOqLydNGYdPjgA6Ot7gcvjvr2D6da+uA==,iv:BzkPsTwNJeuijD4c8+aHyWRprdfeK2NVmyM90Cg9J7k=,tag:4b0F+mrzrWpCynoOmQbicw==,type:str]
    users: ENC[AES256_GCM,data:cAC7uEFvvU9eDfvNHG7Y5icem+0vA6kDnO1Yd2jsT6L1yXpAOPfsn2xNp3STBbq89dy1CAABIKeidPqVI3FNzlzAGQWNlobQJQTe8/FxxQJyKL24EU44ELd4+r4rG6xNp8U09ZUw+ijOARFclXQD/8TOaW4O/9NYO46978BG0o8NGS+1vcHbd0RvlrDwbudMfPR5OT6IN6kX/+bt8P5mgMePJ6wUmLKUQjf9lE3RGbLDjSvYZ7c5xyrKcmVTLDq2i0IyZr4b19ZVnQo7D/4atg+0hShiLRLupABFP7HjLiKJJw==,iv:LZV+TOt6uJPxULoNQ+6+23rjA5PrL9gDdR2NPBChYa8=,tag:c3d9JwhYcPuj3kJ1ug5+tw==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: radicale-configuration
    namespace: other-webapps
    labels:
        reconcile.fluxcd.io/watch: Enabled
sops:
    lastmodified: "2026-01-31T02:35:56Z"
    mac: ENC[AES256_GCM,data:XTGNCT7UTYSGFpzhhmTwWDoWpnYX5BlAzl1h46G3N8VJVXMuJB7eBSEJOjipYgw114FZpeiSmHttBHUlljtOu0TZWXJ5sPonPDNpBvsq6BoMBageDZwFhDbNk7GyUvKn5PWfI/0EdsjbDReWMloM1OpsaiXBXRgLfpnzqs6sBcc=,iv:nZwKjO9IcUCwlvfpZ19wc1yQESyzz++DPm3kQRr03Bs=,tag:gHCZryWjRAiEuB/WVu1RvA==,type:str]
    pgp:
        - created_at: "2025-12-19T04:32:28Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4D3ufNC3rOtvoSAQdAeIn2wnFe2gKhZrIZzr3YdFQbcs7aVDRzUEifzCqQ+k8w
            BKa5h91ElcVbbJ8uYlj0CP+vq3iVgfXmJL1dQA/NgLusHzVPAPHpmoFaJQbUXqbw
            0l4BEFn/ZcxKIV605tuu07/sGVnOxUyV8jVWpmLNR93spUQwoA3WqFM7JIiRTbim
            zP+RMxZGsjTprVzjIf7mcW+s2VIh9eTi56T4zo23RMsrqeg1J4u2TGo2T9L+tiNu
            =+iqw
            -----END PGP MESSAGE-----
          fp: 910E6AB3B6B93104BC0D0F5AD48349BEF211483F
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
