apiVersion: v1
stringData:
    config: ENC[AES256_GCM,data:e1/o6nf56opBO6a+ze3KxQULhsn/D2A86D9rqnUFqHC3xIUo/F4+kb9gkzXaWywyRs+ykdVGeWXla5OTMckPKR+6k/e1qMBiQVRhxRGWwUrxx1RM3d6DZ6hIJmyZhdowHoEDa2qzQ9jekI8gCvfX46nRfP73Idbzgj3GXSfjIxZHcuiSPSoVHuMMr32HhmBlCxvNVJYT+OPJIWwxdXYmaHsze+MOv/sg/4Ru77PdgWtFXae2hFYEm9zzoOOs7Rsr42QQGscn25VDct8pBK+oP0k+DRxqGu8u8380konEakjsO9+8kyYd3f6aVkCRTW/DLyyGOTGsfpSo5QDTbPxJA2IRRpwCPhZDooVnhSph6K867tRmOowowqySXd9KKiW4b5ZAbyn/QfWn9nU6jq4OYsXsccOKhn+0W5gU,iv:RjxEYqGtLowSwybmlUH3DDI6U/uKFkIWcF3WPLOryec=,tag:1+ETc6djY/PoHSd89zW0Rw==,type:str]
    rights: ENC[AES256_GCM,data:VkMhUkiuckUvT5pFO0dj8hnaWu9o8N43A101POkC2pN/qZesA2e7R1FC6sH2pmxcoBqcBXmsvkykw8KE6nZNpWR7R5uFRK0HUGqkjkVQzZ77XNrVEnvNLYuT4Jno72FctoAUcueNqzqxmz2F4oP0mg7yQmuKkQN8CL8HISvGZv3vdLnW2cAiIKwLkLCbS1vTQ5HA0OUhvWl2DCKuPnWONkGAHNshTW87PhhfEzlGlj/9ihHX1JAIbfqmMkthtSx5L+GL4hCYSmZQMB1SIUKba9tURXj5O7ip+R4rFA6wSbGerQTU6bauj6UImUa839q/JnFn6g9XG90V5if0o9x/boWPxnF4jw1lkcpo,iv:xBoII0eRv6YXhrWFyt11YWJJ/bgF1yCeBunrvlKMO/k=,tag:982di1ydi7GitWj9C50SUA==,type:str]
    users: ENC[AES256_GCM,data:cAC7uEFvvU9eDfvNHG7Y5icem+0vA6kDnO1Yd2jsT6L1yXpAOPfsn2xNp3STBbq89dy1CAABIKeidPqVI3FNzlzAGQWNlobQJQTe8/FxxQJyKL24EU44ELd4+r4rG6xNp8U09ZUw+ijOARFclXQD/8TOaW4O/9NYO46978BG0o8NGS+1vcHbd0RvlrDwbudMfPR5OT6IN6kX/+bt8P5mgMePJ6wUmLKUQjf9lE3RGbLDjSvYZ7c5xyrKcmVTLDq2i0IyZr4b19ZVnQo7D/4atg+0hShiLRLupABFP7HjLiKJJw==,iv:LZV+TOt6uJPxULoNQ+6+23rjA5PrL9gDdR2NPBChYa8=,tag:c3d9JwhYcPuj3kJ1ug5+tw==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: radicale-configuration
    namespace: other-webapps
    labels:
        reconcile.fluxcd.io/watch: Enabled
sops:
    lastmodified: "2026-01-31T03:27:48Z"
    mac: ENC[AES256_GCM,data:SOpLciwfKJs1Rg+bpEehdda72x4NT/Cod+3L28mJTFknUZKRTdEQFlM9VqeihS2Ffa5kU08+dQ3aK1BiXqCYQtSjlk1CIdXeF9YlWXdW/dnETK44J8eOKaW2KGCZpk3fodILmRiTPO0JsDtpeQkxYGS6nlwhFy8vwm3aggHdACA=,iv:Hq9zTd3hmTpfbmEyxx7oihx478rNCJmBwA6nmO4mOxU=,tag:MKvKemi6y6boNYaumqPCJQ==,type:str]
    pgp:
        - created_at: "2025-12-19T04:32:28Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4D3ufNC3rOtvoSAQdAeIn2wnFe2gKhZrIZzr3YdFQbcs7aVDRzUEifzCqQ+k8w
            BKa5h91ElcVbbJ8uYlj0CP+vq3iVgfXmJL1dQA/NgLusHzVPAPHpmoFaJQbUXqbw
            0l4BEFn/ZcxKIV605tuu07/sGVnOxUyV8jVWpmLNR93spUQwoA3WqFM7JIiRTbim
            zP+RMxZGsjTprVzjIf7mcW+s2VIh9eTi56T4zo23RMsrqeg1J4u2TGo2T9L+tiNu
            =+iqw
            -----END PGP MESSAGE-----
          fp: 910E6AB3B6B93104BC0D0F5AD48349BEF211483F
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
