---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - calibre-web-automated
  - calibre-web-automated-downloader
  - dispacharr
  - flaresolverr
  - jellyfin
  - m3u-editor
  - plex
  - prowlarr
  - qbittorrent
  - radarr
  - sonarr
