apiVersion: v1
stringData:
    ACCESS_TOKEN_SALT: ENC[AES256_GCM,data:5We8NeCK+4yal7Ynpm7DH69NNuDIwFSVFcdsnaoCua8=,iv:1Ka6ngebbzEWqhB7dMiSEDfME0GoOkS4vBM40sP/rnM=,tag:/TmZRRAO0S7kxU8F2gi5iA==,type:str]
    API_KEY_COINGECKO_DEMO: ENC[AES256_GCM,data:QReE9m3qjED8Qspfl5jPywZw9zximCcgP6fh,iv:JHJkED2LFlPD4AYxw+AHRzgaNHPBKXuicJrk1N5+5sU=,tag:FYFGPmCrpdfMS2/HEMkVjQ==,type:str]
    DATABASE_URL: ENC[AES256_GCM,data:t3CJP4kQj3xcvdUfb57Sj9ZjDRRO/2IOSLtoVcTkie9/8Lgyj9aqNblDYkmDzTAMNf7jumPHrJ22ak5EE2XhdF9ttGqQtNWGv8dC7KkglUA441ETDC8Yq6pCZN1WLHLOLFu5S2gQ,iv:GWIEjxdQvcfW5G+e25GvMOO04xebPESfr3IKs60PSIA=,tag:pNdgGt+IfYxevIsmaVhd7Q==,type:str]
    JWT_SECRET_KEY: ENC[AES256_GCM,data:BbfJyZ5qqre6xtdw1ehZvDwWoRLsM06YwjBEBBnWLeA=,iv:aqZcd3TchDRnPXHGztddzdNcar3vZRxQqtXN/wmIrbc=,tag:TpYC27iDHSA9vm0K1JGgyg==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:bE4U/plmMjAODjfw2PFYKFPfZKucI/OVOpje9RTgUIU3,iv:xxu9gF8ZssMmjUoFlD2brjz5AF6WsGP+eMv4BDoYmf4=,tag:lTVAAqDyZWPxzRS+b4koDw==,type:str]
    REDIS_HOST: ENC[AES256_GCM,data:vuMqTjpeU0UPeEyXd2kWrTy0mHnoRWhP+Kr/KgiXqv3w2xvLYffhNDaB5xhuEaEP,iv:vDTuBeidZqiGFWRSe9+MW7Kb0wjWCRSt/e47KO7j15M=,tag:PjCTkQq5R/4zr+pW/Ni2eA==,type:str]
    REDIS_PASSWORD: ""
    REDIS_PORT: ENC[AES256_GCM,data:XqVNnA==,iv:Cxz2Xe6S2giEDdOHT6R0NT3ypzofl3m0GEHcuC3nnO8=,tag:T2WsjD7/SNq3v87+BA2y5g==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: ghostfolio-configuration
    namespace: other-webapps
    labels:
        reconcile.fluxcd.io/watch: Enabled
sops:
    lastmodified: "2026-01-04T02:34:15Z"
    mac: ENC[AES256_GCM,data:BeBKu5oBephjmlJY8EcRbtiPZX82Dgzsmotzpt8OddbKPjYtmLZMtt9IXk1Hdhu1o3QjIymWieHL6C+D5NNirmYHs4Y7hUF3ZqJRcuN95qxygYXXocw9gqQnvD8epMV+HvWmNSfQSW8rukb2ZFe+y2NiVzN1Lu9yLZuPg/Wkwh0=,iv:dP2tjh/w1eKaJEvJ7U42fj5kKX9sOYj3FS6+L/nIwhM=,tag:+9fM4KIO/TLemey0wo0nFw==,type:str]
    pgp:
        - created_at: "2025-12-19T04:32:28Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4D3ufNC3rOtvoSAQdAeIn2wnFe2gKhZrIZzr3YdFQbcs7aVDRzUEifzCqQ+k8w
            BKa5h91ElcVbbJ8uYlj0CP+vq3iVgfXmJL1dQA/NgLusHzVPAPHpmoFaJQbUXqbw
            0l4BEFn/ZcxKIV605tuu07/sGVnOxUyV8jVWpmLNR93spUQwoA3WqFM7JIiRTbim
            zP+RMxZGsjTprVzjIf7mcW+s2VIh9eTi56T4zo23RMsrqeg1J4u2TGo2T9L+tiNu
            =+iqw
            -----END PGP MESSAGE-----
          fp: 910E6AB3B6B93104BC0D0F5AD48349BEF211483F
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
