---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - ghostfolio
  - immich
  - lubelog
  - ollama
  - paperless-ngx
  - stirlingpdf
  - vaultwarden
  - wallos
  - wedding