apiVersion: v1
stringData:
    WIREGUARD_PRIVATE_KEY: ENC[AES256_GCM,data:PM/YitFLH+YCDDO8zh8LwUNgF8CP0MvXuSBzVpXE4ChXn2L1h/C1+HBkTKw=,iv:/5AoVZuZzj1oglfmBKi+6ATFyuWte2izzqgkX0/BGfs=,tag:0MWxsayfA56NahNShfEPDg==,type:str]
    WIREGUARD_ADDRESSES: ENC[AES256_GCM,data:hGTF+J7UXAixoGX0Pf5P,iv:lYqu2TTDkO5GqncDF4YSoWamYynbnYUqTXKNIhXFVok=,tag:10OJ618D8a0gBEJ+z6I4rg==,type:str]
    FIREWALL_INPUT_PORTS: ENC[AES256_GCM,data:OfZ3VQ==,iv:buGsTGa9qY5tk9o3wR6mnryEhbIblA+shP2b78Gwdqs=,tag:ePyXNFZYEy5jkLfR2uMc4A==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: dispacharr-gluetun
    namespace: media
    labels:
        reconcile.fluxcd.io/watch: Enabled
sops:
    lastmodified: "2026-01-11T21:02:54Z"
    mac: ENC[AES256_GCM,data:McOuTtxaTJt/rFe0OalxsOOo86mbOYkaTnDMgSSo8WWGwbjEDinFulE3RSZez8o7PJSzzyJjhYR1vAcEe7oZ1Bkq385mpy9Kh8Q6Psx/b9PHznq/5n4/80q6zlLhKwCGeo7uGWM5G7m4K3TUnEBWqMFnopNhDF+DN3hms3g74gc=,iv:nLPpFyAvMi02iGYd5e1g2eyBJOEaNW+TKM+bf6jkx7s=,tag:+8ScGQ1WBVsodaiDUKWFng==,type:str]
    pgp:
        - created_at: "2025-12-19T04:32:28Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4D3ufNC3rOtvoSAQdAeIn2wnFe2gKhZrIZzr3YdFQbcs7aVDRzUEifzCqQ+k8w
            BKa5h91ElcVbbJ8uYlj0CP+vq3iVgfXmJL1dQA/NgLusHzVPAPHpmoFaJQbUXqbw
            0l4BEFn/ZcxKIV605tuu07/sGVnOxUyV8jVWpmLNR93spUQwoA3WqFM7JIiRTbim
            zP+RMxZGsjTprVzjIf7mcW+s2VIh9eTi56T4zo23RMsrqeg1J4u2TGo2T9L+tiNu
            =+iqw
            -----END PGP MESSAGE-----
          fp: 910E6AB3B6B93104BC0D0F5AD48349BEF211483F
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
