apiVersion: v1
stringData:
    accessKeyId: ENC[AES256_GCM,data:hD+FQJIODlx40rD/PhHymnes0yEhb73hi0I=,iv:SEaUPBGuOchpWqsRU3P+uxAym8UoDTuLS8yQ7Ap9eBA=,tag:Av/7134R209PuiKEEHew4Q==,type:str]
    secretAccessKey: ENC[AES256_GCM,data:lhO3xR5BckoBgIzBIv3LdUIdFwo5bjZmP4urPjeFjB7F/BBwSuqdmiIoKB2KiKoAKRbnYoNQWv4MnSBqBpaj6w==,iv:yqhtO/Av25gQeKueDTyIVo88RMiYMy3etjdMFTgdagk=,tag:upnENlNuKnZbCtimvVjVbQ==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: loki-configuration
    namespace: monitoring
    labels:
        reconcile.fluxcd.io/watch: Enabled
sops:
    lastmodified: "2026-01-05T02:46:30Z"
    mac: ENC[AES256_GCM,data:WOO73CdcmTQi+1PXrFTtiTBswJBL+jP2iK9bOKijoeOcvUB6ZaemfVCjwUARfYKI4+u3QkYMlULG7LEUrcUNThjcsFhyMUyhdtpZY62hP17l6Hxe8R5q/OhzE4iM5+ihWpLrBONQF61QmquLOlcGtJBxocjvhBm3oJYArxsEk+w=,iv:aO9IJW5gv7DavbMxWYuilDbVPCRXCKJTCBZbr7XXVg0=,tag:8kwCep8NA1RvTqMy+usbsw==,type:str]
    pgp:
        - created_at: "2025-12-19T04:32:28Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4D3ufNC3rOtvoSAQdAeIn2wnFe2gKhZrIZzr3YdFQbcs7aVDRzUEifzCqQ+k8w
            BKa5h91ElcVbbJ8uYlj0CP+vq3iVgfXmJL1dQA/NgLusHzVPAPHpmoFaJQbUXqbw
            0l4BEFn/ZcxKIV605tuu07/sGVnOxUyV8jVWpmLNR93spUQwoA3WqFM7JIiRTbim
            zP+RMxZGsjTprVzjIf7mcW+s2VIh9eTi56T4zo23RMsrqeg1J4u2TGo2T9L+tiNu
            =+iqw
            -----END PGP MESSAGE-----
          fp: 910E6AB3B6B93104BC0D0F5AD48349BEF211483F
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
