apiVersion: v1
stringData:
    APP_URL: ENC[AES256_GCM,data:z6hra87XlqVagx/UncXXhSZ1ZiQ=,iv:f8fjelBx/sJULnWvrK5tvKIdOzL0PLSNqYRigeJxwSo=,tag:1ucNBF7nagP1fFaJdlSIEA==,type:str]
    DB_CONNECTION: ENC[AES256_GCM,data:WbhgSCg=,iv:e807jE7Lv87YTPIJUt81YG+npbDJoXOavG3JpLX2dVo=,tag:UrLlpETxxfa3XdBLydwIkw==,type:str]
    DB_DATABASE: ENC[AES256_GCM,data:955FY33V5KhW,iv:Jrw3kaUT+A1EOC7S2GOL4Po2KFmYeTtOeDlJIod2XkQ=,tag:PA6XzgzRUSm/0mClJIJX+w==,type:str]
    DB_HOST: ENC[AES256_GCM,data:QrkQHRLdwxwj4x7es4M0yzGtbTzUCWNFtZY3AYfGk6LFOp2YHqAGxAPSXA==,iv:GtjbVXC1BJxRM+4we+O+3JwqLwXif86Nv35QiI31tJE=,tag:o8358wTaKU+2+lmAAVyBBA==,type:str]
    DB_PASSWORD: ENC[AES256_GCM,data:whXmLSuWEEEdCdD1Xz6UtoPRvusRLw5OT4/uCMif/VI=,iv:mAddXC+7T3yY3mgJ9erl+2piB4OoWhEg/XdioIyfQmg=,tag:wqMC6QvtGTeSjQ5cJ7PjYA==,type:str]
    DB_PORT: ENC[AES256_GCM,data:4FY6Ww==,iv:Z0WUJXNDJLviHqk13if7dBeC1Q48WvXyZEwPvwsL4sM=,tag:7CMgF7htnrJWKdevhrfdog==,type:str]
    DB_USERNAME: ENC[AES256_GCM,data:mEswrcxeSfWN,iv:CZ5eUx4wQ4QofeTt1XIXNIKxLK24miO5vK/cnQKaUV8=,tag:VPHqyQE21ofZX/9MYlSwwQ==,type:str]
    MAX_CHANNELS: ENC[AES256_GCM,data:IdMY93do,iv:1XoijHKNBbyf3eNf3/LRzu8X/JLfXjHysstki4wCKaM=,tag:wyHZJvpDfRGn/AtauLKx0g==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:IAJcAnZLdxaYqPF5qlgsiZyrHwU+ob5SezxEWSGklMI=,iv:+FAEJZaRGGzqQ8L5sWmSMjGgx4t+hHduKw0wo9UMqJY=,tag:v8CZYlZOL1eavGQqCM7baw==,type:str]
    REDIS_HOST: ENC[AES256_GCM,data:has1eupnTIfbhqQhjVockurtasG8mMlw3PSpEKFM3RMpU3GLXKAygQ==,iv:F8qd3QqiBGSVWPNxFwCYX4LhVnD4IxuGyhH5UBk266Y=,tag:uC6uRDuhWNC+AgTkCBiL6w==,type:str]
    REDIS_SERVER_PORT: ENC[AES256_GCM,data:U6B/fg==,iv:uHH3qffSar18T7ngfXh3cDWgQsrGX+j3ND7NyM9he4A=,tag:Ez15X14GT7ISk4GfqvKC7g==,type:str]
    REVERB_HOST: ENC[AES256_GCM,data:WAamlL+h9ZlprGkJ,iv:SGvZG/j7OMeZEHmCL8t1F9AmMM4jXYeJW/JwtLn84m8=,tag:NnBGIA//4/Rozzj+LbDiUQ==,type:str]
    REVERB_SCHEME: ENC[AES256_GCM,data:HkfpwUU=,iv:vteVVVWHuP449BEQd2fBMAXE6D44DF6pyKrskAdxPXM=,tag:JRI2QcVQg0QNISz66fg9/Q==,type:str]
    TZ: null
kind: Secret
metadata:
    creationTimestamp: null
    name: m3u-editor-configuration
    namespace: media
    labels:
        reconcile.fluxcd.io/watch: Enabled
sops:
    lastmodified: "2026-01-04T01:21:52Z"
    mac: ENC[AES256_GCM,data:FndEJ/gevRmtyd4vOLalS3P4AKbutdtZHRLJ/DSZ9bH3rOsOhXKMsXGT7mbU/YuyG4F/6DeiUu0GNV4Wgc4LtPn79+lOqTT2/2PnhMPpB49whZ1HVo2AvQpZv7Y2XunArC7lnNbei5qgW013mXxzHUzs7LTcTMVtLN4FWjk6OXU=,iv:C12wFtTO99q1WCkdJpFpl+IH5ulynHfPOMf9iu9aDXQ=,tag:YJf6v4c92o6YlCGIDV3EKQ==,type:str]
    pgp:
        - created_at: "2025-12-19T04:32:28Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4D3ufNC3rOtvoSAQdAeIn2wnFe2gKhZrIZzr3YdFQbcs7aVDRzUEifzCqQ+k8w
            BKa5h91ElcVbbJ8uYlj0CP+vq3iVgfXmJL1dQA/NgLusHzVPAPHpmoFaJQbUXqbw
            0l4BEFn/ZcxKIV605tuu07/sGVnOxUyV8jVWpmLNR93spUQwoA3WqFM7JIiRTbim
            zP+RMxZGsjTprVzjIf7mcW+s2VIh9eTi56T4zo23RMsrqeg1J4u2TGo2T9L+tiNu
            =+iqw
            -----END PGP MESSAGE-----
          fp: 910E6AB3B6B93104BC0D0F5AD48349BEF211483F
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
