apiVersion: v1
stringData:
    BLIZZARD_CLIENT_ID: ENC[AES256_GCM,data:ERF+vwgGaiL43hP4LyXaOQ6OobS8vgUmK5h9ks1XIHM=,iv:iZ+Wn+PanzdXAedKbg+RJmjvSZorgoDZ7dtGLAiZiMU=,tag:uUkrNbMa1pfjbwDjBu1g1A==,type:str]
    BLIZZARD_CLIENT_SECRET: ENC[AES256_GCM,data:A2PLuxkD0Xrm8NQvH9y2thK20B+7+LrLAwsv81TBygo=,iv:c/2ZCcZ+F1tHsdO+RPolEXR8Rj7UdYbetYZqk1zxVKQ=,tag:ro0aPlMA0rz4eqoj9YWOZg==,type:str]
    CONFIG_LAST_UPDATE_PATH: ENC[AES256_GCM,data:+gYnnKTD0jgYEMlX91XgHaoLOSDE,iv:VTX05gKpxGplRdql7ebS8p7d7ZbJn0dtrIPwMpYdjbo=,tag:PFTOw3h3XnWnF0jb5JmIAQ==,type:str]
    DATABASE_URL: ENC[AES256_GCM,data:oFujBmiIBA7LNRqrSZ2lACyNNLlB7CHnyBK30hnJJ/wnnwvjWzeBnKciyeAHkTSUKQHM383oJsl+bH7vFE4auV07odRVDDNPdpTuzbxF1h31+KM8TRsT6WjvyRkOIP/y0XT+3YNKLQNBHtPHUvPvLv9axwes,iv:WeSH16hhzTOcEGgVUsIDp+mxTilH74bWWt0F4/OtZik=,tag:eplLKAP6joQuhFmzgxXWRg==,type:str]
    DISCORD_TOKEN: ENC[AES256_GCM,data:RatLh4QhkU+eDmNqVGN3Sh0lUxtxu3iWt5NQNezsMAvNzrdwg/GfF6Mx8TEmkfX+yGM/X3fFcNBrnDXIlDw3Nowpan9JA/nh,iv:3xxry9ewSszzQxG9Yx881miRNOeKuL7WkN28rFE6H94=,tag:4s+7+hKCUgKAdzVKdqOoNQ==,type:str]
    ENABLE_AUCTION_SCANNER: ENC[AES256_GCM,data:3AQASLQ=,iv:HhhooWFkXD9sAJnMLL7tB/ybKf5N6R6fyFabhj574LI=,tag:C9UqEghF+OzJXvQfuMk43g==,type:str]
    ENABLE_DISCORD: ENC[AES256_GCM,data:Hcnf0Q==,iv:wufov6nbrIEOmJwBgSocWbgYtAWahZilZ00HNcqxB+o=,tag:j5Vpde/KPDl0i/JoZjZmow==,type:str]
    INFLUXDB_BUCKET: ENC[AES256_GCM,data:wGnllJ4662TE0/fMw48UP/DYYQ==,iv:IxXnv3IRJdCWAk1J9nYgbU8UF1lSh/adsYjFDAZRkhI=,tag:XeGbY3PD70WmYygEPnk8mQ==,type:str]
    INFLUXDB_HOST: ENC[AES256_GCM,data:TFGVb3dFVTlF4tHRj0PjJC/rjm4dI3J9mdIm/3kfFrcoWeJ4Kb5M0uRyRA2P8ucu8Q/83i0Z/K3v3A==,iv:OKdGuUBuqF/7B3ru3CNFh3hEvQ5UVuM8/h74vQVGnG0=,tag:UaO0cmC7sSLKiWclmYr2KQ==,type:str]
    INFLUXDB_ORG: ENC[AES256_GCM,data:FlQFyaLGRiNBdAik3SYD,iv:sEJNktXP1NHO7m44W/aOSRVVnz5ciCBAcWGwr+mCf8I=,tag:y9FhWfgLUtGOdVmU8pEXgQ==,type:str]
    INFLUXDB_TOKEN: ENC[AES256_GCM,data:K8jhQ6Q/bYvMPZGCbprUW8OLZNXGoV4HhsfXgPUNCpObQ3WNkz8ROaJAMCl8rd9c9l1Uizel3llGWJJZajUjpYaDQobkyBZIwaTbkkwhKXd96corsDRKWw==,iv:7Livayp2JQafBFWzZRY7i+qnia27UiPQd/DP8yNTQ00=,tag:BYAsIk5qb19Sd3aAaEujkQ==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:rw0EXbqWEbCbmKXy5OuQR2ZnaektCcli8YCmAlC6bCE=,iv:rhZDT72nUdo520p/rJeYf7XE3d1UAMMMYMQJ1ibMJPY=,tag:IqlYcgwV1ed/RrDZVVtXvg==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: bot-configuration
    namespace: small-indie-bot
    labels:
        reconcile.fluxcd.io/watch: Enabled
sops:
    lastmodified: "2026-01-04T01:52:34Z"
    mac: ENC[AES256_GCM,data:EUmKCHJaHPoqiCeyfK0P5Z7DyYhEqd9IurWoXViYAUyNrdv1Z7PanG1QEddRNkTxtZWrNBYqP+VqemTPkPAWZzobGUVr1c5Jh5/PnhcRxV5qeHmcnGEUVMIZEIc9gAHtSC1i0yIiSe5FU7bk3E7TcMuFTxggzIScASjxkvQBD3U=,iv:t+D5E7Lw0zSoe+wpUWuUzApAmlBmy2MINy4/5h76ahc=,tag:ipEtXrqJZeSo2gwKsBzlPQ==,type:str]
    pgp:
        - created_at: "2025-12-19T04:32:28Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4D3ufNC3rOtvoSAQdAeIn2wnFe2gKhZrIZzr3YdFQbcs7aVDRzUEifzCqQ+k8w
            BKa5h91ElcVbbJ8uYlj0CP+vq3iVgfXmJL1dQA/NgLusHzVPAPHpmoFaJQbUXqbw
            0l4BEFn/ZcxKIV605tuu07/sGVnOxUyV8jVWpmLNR93spUQwoA3WqFM7JIiRTbim
            zP+RMxZGsjTprVzjIf7mcW+s2VIh9eTi56T4zo23RMsrqeg1J4u2TGo2T9L+tiNu
            =+iqw
            -----END PGP MESSAGE-----
          fp: 910E6AB3B6B93104BC0D0F5AD48349BEF211483F
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
