
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: bot
  namespace: small-indie-bot
spec:
  interval: 5m
  upgrade:
    force: true
  chart:
    spec:
      chart: app-template
      version: 4.5.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      interval: 5m
  values:
    defaultPodOptions:
      imagePullSecrets:
       - name: ghcr-image-pull-secret
    controllers:
      app:
        enabled: true
        containers:
          app:
            image:
              repository: ghcr.io/anthonytam/small-indie-bot
              tag: latest
            envFrom: &envFrom
              - secret: bot-configuration
      postgres:
        enabled: true
        containers:
          postgres:
            image:
              repository: postgres
              tag: 18.2
            envFrom: *envFrom
      influxdb:
        enabled: true
        containers:
          influxdb:
            image:
              repository: influxdb
              tag: 2.8.0
    service:
      postgres:
        enabled: true
        controller: postgres
        ports:
          http:
            port: 5432
      influxdb:
        enabled: true
        controller: app
        ports:
          http:
            port: 8086
    persistence:
      config:
        enabled: true
        type: nfs
        server: nfs.local.tam.land
        path: /nfs-share/small-indie-bot/bot/config
        advancedMounts:
          app:
            app:
              - path: /app
      pgdata:
        enabled: true
        type: nfs
        server: nfs.local.tam.land
        path: /nfs-share/small-indie-bot/bot/postgres
        advancedMounts:
          postgres:
            postgres:
              - path: /var/lib/postgresql/data
      influxdb-data:
        enabled: true
        type: nfs
        server: nfs.local.tam.land
        path: /nfs-share/small-indie-bot/bot/influxdb
        advancedMounts:
          influxdb:
            influxdb:
              - path: /var/lib/influxdb2