---
apiVersion: v1
kind: Secret
metadata:
  name: tamland-tls
  namespace: admin
type: Opaque
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: "tamland-cert"
  namespace: admin
spec:
  secretName: "tamland-tls"
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: "tam.land"
  dnsNames:
    - "tam.land"
    - "*.tam.land"
---
apiVersion: traefik.containo.us/v1alpha1
kind: TLSStore
metadata:
  name: tamland-tlsstore
  namespace: admin
spec:
  defaultCertificate:
    secretName: "tamland-tls"
---
apiVersion: homerow.ca/v1
kind: SyncSecret
metadata:
  name: tamland-tls-secret
spec:
  secret:
    name: tamland-tls
    namespace: admin
  destinationNamespaces:
    - media
    - monitoring
    - other-webapps
    - smart-home