apiVersion: v1
stringData:
    LANG: ENC[AES256_GCM,data:95GUzlnj7r5Ts40=,iv:hugjJ9M44jdj2X6dQfW/wiy0x59zaim9Fvmu0SAD+Qc=,tag:uk74YQw3HoR8EukEBeiiAg==,type:str]
    LC_ALL: ENC[AES256_GCM,data:ugIOKiolhfuE030=,iv:OQ7cNV3zyp6uWh50qmFePygFuHGVwLGk4keAr23fqT4=,tag:xO78TMw7wqOBiAs6Clmv/A==,type:str]
    LOGGING__LOGLEVEL__DEFAULT: ENC[AES256_GCM,data:FI0FBTo=,iv:QgUJ4au16Fsz3D3ib0OinioalTMFOdd3P+3z0nmRDyc=,tag:zobUIrI/ejBhUC+ZSAj+FQ==,type:str]
    MailConfig__EmailFrom: ENC[AES256_GCM,data:O46oBPhuP9eGYqUsnOui0NPZfrKuzw==,iv:DPOLwLEZdvilYZQIaqrWv2oZdr+Bbechp9iH/eZrM34=,tag:xht8gQBwI/JSx5aKEMS/NA==,type:str]
    MailConfig__EmailServer: ENC[AES256_GCM,data:/leY3oxFF/uz2z1EehzC+Ojp39ZPlCUESiTmLwq0qjc=,iv:5Z/QayTU3EZYYHEL73gFYOc5JN0TGigAkp5KZhB/ZRk=,tag:1ahQW5dU/PyPsNxj/GC0Qg==,type:str]
    MailConfig__Password: ""
    MailConfig__Port: ENC[AES256_GCM,data:jO9tyA==,iv:7oQRJqj10eNHLq7cGMrh0WfGut4FH/wbUllVhGA6zSQ=,tag:fezfQ4L9gQTVcsnT2EJoqw==,type:str]
    MailConfig__UseSSL: ENC[AES256_GCM,data:Zdsly8Q=,iv:bP1iGmZl4d4ooB1a4VHMpHf+Ewc3ilVuJSPKXGbuM/w=,tag:e9qH9NBNbitcnv7rNyKaBg==,type:str]
    MailConfig__Username: ""
kind: Secret
metadata:
    creationTimestamp: null
    name: lubelog-configuration
    namespace: other-webapps
    labels:
        reconcile.fluxcd.io/watch: Enabled
sops:
    lastmodified: "2026-01-04T02:37:35Z"
    mac: ENC[AES256_GCM,data:Me4rAVikqXLNZGIcelDT6466uNn/zW+5/Oq4UhXOLIA9NS5YWYszHjZ1hjOEehHGz2TW5dnNnccTY38pwj6dvuFokbflN902HqV2nXpsJlDWWQzSJ6A9CRhktBA2tQZvQtFOBU0rHfEVSH843HaF0bRIGsIGjp+SFhPS620Hy30=,iv:UkgzbpWd+oqb3HsCaDVbKWecfe36NQIfbow/1PZajKg=,tag:c624r+U987osdf2NYeG6WA==,type:str]
    pgp:
        - created_at: "2025-12-19T04:32:28Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4D3ufNC3rOtvoSAQdAeIn2wnFe2gKhZrIZzr3YdFQbcs7aVDRzUEifzCqQ+k8w
            BKa5h91ElcVbbJ8uYlj0CP+vq3iVgfXmJL1dQA/NgLusHzVPAPHpmoFaJQbUXqbw
            0l4BEFn/ZcxKIV605tuu07/sGVnOxUyV8jVWpmLNR93spUQwoA3WqFM7JIiRTbim
            zP+RMxZGsjTprVzjIf7mcW+s2VIh9eTi56T4zo23RMsrqeg1J4u2TGo2T9L+tiNu
            =+iqw
            -----END PGP MESSAGE-----
          fp: 910E6AB3B6B93104BC0D0F5AD48349BEF211483F
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
