---
apiVersion: v1
kind: Secret
metadata:
  name: anthonyandjessielove-tls
  namespace: admin
type: Opaque
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: "anthonyandjessielove-cert"
  namespace: admin
spec:
  secretName: "anthonyandjessielove-tls"
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: "anthonyandjessie.love"
  dnsNames:
    - "anthonyandjessie.love"
    - "*.anthonyandjessie.love"
---
apiVersion: traefik.containo.us/v1alpha1
kind: TLSStore
metadata:
  name: anthonyandjessielove-tlsstore
  namespace: admin
spec:
  defaultCertificate:
    secretName: "anthonyandjessielove-tls"
