apiVersion: v1
stringData:
    WORDPRESS_DB_HOST: ENC[AES256_GCM,data:eIgTXbaQvMqZ+ZNDRmpw5BYxTJcPBNCHXzi8vyuWQf0pi0gjnvyPkhvmFu0t2DWBg+XLQw==,iv:LlC/RnMz7z0D0cpAgk8tCKt3nxkTXyw7nv16E65QfyU=,tag:DW8bqfOWd1AmhkykTAFKbg==,type:str]
    WORDPRESS_DB_USER: ENC[AES256_GCM,data:zpimvnJ3UL8Cqw==,iv:tJMQZuiiejbJ+47UuU08lAylZyZOsgFT0ZtSLRk9/vs=,tag:CznBzvMqoIwJltXGhO6Yjg==,type:str]
    WORDPRESS_DB_PASSWORD: ENC[AES256_GCM,data:NDJRy6K7DeWvqWk2/B/DkoflqRNucztRAW0DC/cm/4Y=,iv:jnu+r0qc7rs032wSjlhJULk71nrNiKq6oHmpHIu4pu0=,tag:uuCuUVG6D6cUB+BQyZzBRg==,type:str]
    WORDPRESS_DB_NAME: ENC[AES256_GCM,data:E7Nren3kdV0foA==,iv:JQ9XXnShvMnSSS45DVskdALmtmyEqh95IeRn8ZlEwZ4=,tag:FMlM9XtX1Qb1rDYFwoxWyA==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: wedding-wp-secrets
    namespace: other-webapps
    labels:
        reconcile.fluxcd.io/watch: Enabled
sops:
    lastmodified: "2025-12-23T01:23:20Z"
    mac: ENC[AES256_GCM,data:hTYcUbwCz8bJMqYg85qGt+5VMdBdygvGJZFXocmomdKW522lHy/nc3volOnKwlrqYS/hYnTtEU36GsFFFY4QuiAvD7bhoKundID+iMA0x+KZnVaZIhsRTzs6DMAzy5q5sz328jOoUHjuV7nyNnIwDjzyrxrAnistE2knIynZtdk=,iv:IgnQS0UF4NnKhRWgL8Vyy5zSdgkq11oFg4++8KoqaB0=,tag:G4u16aFCypAe9iTQWRQmIw==,type:str]
    pgp:
        - created_at: "2025-12-19T04:32:28Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4D3ufNC3rOtvoSAQdAeIn2wnFe2gKhZrIZzr3YdFQbcs7aVDRzUEifzCqQ+k8w
            BKa5h91ElcVbbJ8uYlj0CP+vq3iVgfXmJL1dQA/NgLusHzVPAPHpmoFaJQbUXqbw
            0l4BEFn/ZcxKIV605tuu07/sGVnOxUyV8jVWpmLNR93spUQwoA3WqFM7JIiRTbim
            zP+RMxZGsjTprVzjIf7mcW+s2VIh9eTi56T4zo23RMsrqeg1J4u2TGo2T9L+tiNu
            =+iqw
            -----END PGP MESSAGE-----
          fp: 910E6AB3B6B93104BC0D0F5AD48349BEF211483F
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
