apiVersion: v1
stringData:
    MARIADB_ROOT_PASSWORD: ENC[AES256_GCM,data:T7yEUrKG7Faq3eW/LDKjJ/QNatYZlRtQ8U+UsGuQ28s=,iv:D4c756kWVoji0kdlPsXfL96EmoKRWQFbC/3cQfLyz8Y=,tag:JOThqeZMETxaQa7Goq2+Qg==,type:str]
    MARIADB_USER: ENC[AES256_GCM,data:as2gP88uTTK7Mg==,iv:SpKepXW35qrIh9lUUKcxi0VB4R27tTYT+rSakxBt4s0=,tag:DuuNk79PhFGDf2Vcgpg7Mw==,type:str]
    MARIADB_PASSWORD: ENC[AES256_GCM,data:cQu/4qKDcFJLO++nKaeta/trck4+6QwDrm3yMUcCpNQ=,iv:cklAE8lpUnH2tSN/0gDfKD5LRpbnshrLRCDLjZUJO4o=,tag:Be/npI/dlGLYHjEewTLDIw==,type:str]
    MARIADB_DATABASE: ENC[AES256_GCM,data:RcfJlHx6cZ2nyQ==,iv:t/4DS4FTSBPFFaqerendjBq670TcPMK6ucoFL8ZMHT0=,tag:TfcNw8hOOsarhRvv0ZhHrQ==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: wedding-mariadb-secrets
    namespace: other-webapps
    labels:
        reconcile.fluxcd.io/watch: Enabled
sops:
    lastmodified: "2025-12-22T22:48:48Z"
    mac: ENC[AES256_GCM,data:Awxi7VGRcBsT086bLGTS76SOh5VJfEYvbWZbq+0JHn/H2V5hZbIkBYg6IwgJzu3LFpMX1zsQxiI7HH7iRFeG7XVAXpAIo20Ac8VDKaaIfTkSHNjW4eigmw48S29wbES7a32Qiqci3soLNv6Wrgk6bLBZEs/rHRCgnbdYpiFTyMA=,iv:enV0IBcCVSxy0fcJoB3vMJyB8s+Ipt9A3PTZmCJbxA4=,tag:8qVybr6EZ7x3nkXYWIz+YQ==,type:str]
    pgp:
        - created_at: "2025-12-19T04:32:28Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4D3ufNC3rOtvoSAQdAeIn2wnFe2gKhZrIZzr3YdFQbcs7aVDRzUEifzCqQ+k8w
            BKa5h91ElcVbbJ8uYlj0CP+vq3iVgfXmJL1dQA/NgLusHzVPAPHpmoFaJQbUXqbw
            0l4BEFn/ZcxKIV605tuu07/sGVnOxUyV8jVWpmLNR93spUQwoA3WqFM7JIiRTbim
            zP+RMxZGsjTprVzjIf7mcW+s2VIh9eTi56T4zo23RMsrqeg1J4u2TGo2T9L+tiNu
            =+iqw
            -----END PGP MESSAGE-----
          fp: 910E6AB3B6B93104BC0D0F5AD48349BEF211483F
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
