apiVersion: v1
stringData:
    WORDPRESS_DB_HOST: ENC[AES256_GCM,data:Btmb5y3lJYlg0t0r3en9JtaNNjKr0HWKInIWUq/IjsRrWmm1BWw276qEOIfbL4s=,iv:LsLs5BI7VpQ0V2Bq4V5pFOvFXEz9OIh82oCsCXNqj8I=,tag:iLUbNJveLEZ5um5j86yrlQ==,type:str]
    WORDPRESS_DB_USER: ENC[AES256_GCM,data:zpimvnJ3UL8Cqw==,iv:tJMQZuiiejbJ+47UuU08lAylZyZOsgFT0ZtSLRk9/vs=,tag:CznBzvMqoIwJltXGhO6Yjg==,type:str]
    WORDPRESS_DB_PASSWORD: ENC[AES256_GCM,data:NDJRy6K7DeWvqWk2/B/DkoflqRNucztRAW0DC/cm/4Y=,iv:jnu+r0qc7rs032wSjlhJULk71nrNiKq6oHmpHIu4pu0=,tag:uuCuUVG6D6cUB+BQyZzBRg==,type:str]
    WORDPRESS_DB_NAME: ENC[AES256_GCM,data:E7Nren3kdV0foA==,iv:JQ9XXnShvMnSSS45DVskdALmtmyEqh95IeRn8ZlEwZ4=,tag:FMlM9XtX1Qb1rDYFwoxWyA==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: wedding-wp-secrets
    namespace: other-webapps
    labels:
        reconcile.fluxcd.io/watch: Enabled
sops:
    lastmodified: "2025-12-22T22:59:07Z"
    mac: ENC[AES256_GCM,data:C4Gyn/Xo9XXFbo/CmlEQg1mSip7odbF187vs2Zwpcd/2z/a0I+Q7cSuu6Tog3tfKaAwQhvJwOy97IOC54KiyoGXNWeSpxvuMFT6hba9JUBzJJhUl6JLvMUvOmxGTT1WqMHjUB4ocmp7G5T4u83MqPUw538pDNDd9D6jxLSXwAis=,iv:fPTLrhJnjCQZoiwToxptPI8zsHtGYOuiK/yFfVyvTGg=,tag:ZIbMaxvOnGMltn0+/Z+nig==,type:str]
    pgp:
        - created_at: "2025-12-19T04:32:28Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4D3ufNC3rOtvoSAQdAeIn2wnFe2gKhZrIZzr3YdFQbcs7aVDRzUEifzCqQ+k8w
            BKa5h91ElcVbbJ8uYlj0CP+vq3iVgfXmJL1dQA/NgLusHzVPAPHpmoFaJQbUXqbw
            0l4BEFn/ZcxKIV605tuu07/sGVnOxUyV8jVWpmLNR93spUQwoA3WqFM7JIiRTbim
            zP+RMxZGsjTprVzjIf7mcW+s2VIh9eTi56T4zo23RMsrqeg1J4u2TGo2T9L+tiNu
            =+iqw
            -----END PGP MESSAGE-----
          fp: 910E6AB3B6B93104BC0D0F5AD48349BEF211483F
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
