apiVersion: v1
stringData:
    garage.toml: ENC[AES256_GCM,data:6oaCps3Ru++clZjULQLswzDZmFT7/xA7m07W2V2uv6+S8Yhh5+Ss+s5cQT/SP+wGnF6aYIMRene+DlCb/YzZSpMCie1MP+gpollgBXKYasiUx7SrPlaJ21Oo1pL4vsvpZQbYMcBrmhCjjxrlx6G7xRovO5U83UUVvq8mpiRpeOUrpYuDIJCQ2h0tVh/7p3dGjo1VeoL+MI8/j/gjWB5UfucXPNCOxGTmxBwl4he7iAm5GekSmboT0WaEQOwpPt5mcKNbxOV34QPxduxZYQb4xqYPadHxXzr+xKzoqHNH+GykEU3J/BKvUMHaHd0kzcsN2WZvfUQdm5a1dvClJLSYpKMvGDI+B0oZwy4T5ttVc6HnWO8qh4g34mkhjq0WDa3IVK1CoOkDA+lLAZYB0eYbHE9RE9YkzdSgaZO/LyH55dgrVUsOzsNSVlkJewJxPsje5U0w9RnmuZPhFv7dJZdww4O0h2wd1AdgySQi9+OT+ws6I6ky+IBvJ7DQowAB2/x3AMP2PBJaQMps4TARB39XjSgTV5Juu6Y5+gieiZnuOG6R223dMllhp82T5NFaEqFti7NblQBYDOXfy2IQFpSwfl+SJmMEKiwFTw860AfGXMOr1+ndlYl5BEGUpKVfYPh9TwC1Lw7a1QfaibxSZofqm/q63Omw28f8APekkbC0Vqk4NTF7JGidEofxjRChh41XbPCDQZ5ETzTsZexhpfZB29xbs0gC3zM3NMyDDtuwagCcAnhfpPRHcHzBGKHw5ESsbUMFwk1mXOVBxKOxxXrST0ERQqf4B3J19J+vQck9zdwZpE4JOFzZdhh4hAy8X0jvE3Oeu1scAau9H7Scnng3hCCvcCzYNq/QmGE=,iv:chmiymg7jtdaymw6fgWJPuNGGNklLdwShKiSYfzZbCY=,tag:9a9+JDpI/wyrsr/JM0yKmg==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: garage-configuration
    namespace: admin
    labels:
        reconcile.fluxcd.io/watch: Enabled
sops:
    lastmodified: "2026-01-05T01:53:55Z"
    mac: ENC[AES256_GCM,data:I2U934KPfhJU0C7Yp6vfKdL0tYy+W2bRPZ2VMcfju4laz4p6sDbVcaQYZhojzRZOlvoZWjDAofNJlgqHvcKPQHkNE6O0T7VzOhkWOAUeinrN9Vo68S8wxQI90zfjpj9Z8Mu4ZRddIpOSMDU92QhFsth62TxiHoF4GY7LeeNKmgY=,iv:psP/OlgZ1VHGdypVd8Gc+qeAKHorFRyD5RRnKWEgmbU=,tag:C43P3l2ECfgWYq8AaFkMzA==,type:str]
    pgp:
        - created_at: "2025-12-19T04:32:28Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4D3ufNC3rOtvoSAQdAeIn2wnFe2gKhZrIZzr3YdFQbcs7aVDRzUEifzCqQ+k8w
            BKa5h91ElcVbbJ8uYlj0CP+vq3iVgfXmJL1dQA/NgLusHzVPAPHpmoFaJQbUXqbw
            0l4BEFn/ZcxKIV605tuu07/sGVnOxUyV8jVWpmLNR93spUQwoA3WqFM7JIiRTbim
            zP+RMxZGsjTprVzjIf7mcW+s2VIh9eTi56T4zo23RMsrqeg1J4u2TGo2T9L+tiNu
            =+iqw
            -----END PGP MESSAGE-----
          fp: 910E6AB3B6B93104BC0D0F5AD48349BEF211483F
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
