---
apiVersion: v1
kind: ConfigMap
metadata:
  name: traefik-config
  namespace: admin
data:
  dynamic.yml: |
    http:
      middlewares:
        localOnly:
          ipWhiteList:
            sourceRange:
              - 10.200.0.0/24
      routers:
        api:
          rule: "Host(`traefik.local.tam.land`)"
          entrypoints: ["websecure"]
          service: "api@internal"
          middlewares:
            - "localOnly@file"
